/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const BulkGenerateDtoSchema = z.object({
    termId: z.string().uuid(),
    classIds: z.array(z.string().uuid()).optional(),
    streamIds: z.array(z.string().uuid()).optional(),
});
export type BulkGenerateDto = z.infer<typeof BulkGenerateDtoSchema>;

export const BulkGenerateFailureDtoSchema = z.object({
    studentId: z.string(),
    error: z.string(),
});
export type BulkGenerateFailureDto = z.infer<typeof BulkGenerateFailureDtoSchema>;

export const BulkGenerateResultDtoSchema = z.object({
    succeeded: z.array(z.string()),
    failed: z.array(BulkGenerateFailureDtoSchema),
});
export type BulkGenerateResultDto = z.infer<typeof BulkGenerateResultDtoSchema>;
