/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const BulkGenerateAdhocInvoicesDtoSchema = z.object({
    termId: z.string().uuid(),
    classId: z.string().uuid(),
    feeCategoryIds: z.array(z.string().uuid()).min(1),
    studentIds: z.array(z.string().uuid()).min(1),
});
export type BulkGenerateAdhocInvoicesDto = z.infer<typeof BulkGenerateAdhocInvoicesDtoSchema>;

export const BulkAdhocInvoiceSuccessDtoSchema = z.object({
    studentId: z.string(),
    invoiceIds: z.array(z.string()),
    alreadyBilledCategoryIds: z.array(z.string()).optional(),
});
export type BulkAdhocInvoiceSuccessDto = z.infer<typeof BulkAdhocInvoiceSuccessDtoSchema>;

export const BulkAdhocInvoiceFailureDtoSchema = z.object({
    studentId: z.string(),
    error: z.string(),
});
export type BulkAdhocInvoiceFailureDto = z.infer<typeof BulkAdhocInvoiceFailureDtoSchema>;

export const BulkAdhocInvoiceSkipDtoSchema = z.object({
    studentId: z.string(),
    alreadyBilledCategoryIds: z.array(z.string()),
});
export type BulkAdhocInvoiceSkipDto = z.infer<typeof BulkAdhocInvoiceSkipDtoSchema>;

export const BulkGenerateAdhocInvoicesResultDtoSchema = z.object({
    succeeded: z.array(BulkAdhocInvoiceSuccessDtoSchema),
    failed: z.array(BulkAdhocInvoiceFailureDtoSchema),
    skipped: z.array(BulkAdhocInvoiceSkipDtoSchema),
});
export type BulkGenerateAdhocInvoicesResultDto = z.infer<typeof BulkGenerateAdhocInvoicesResultDtoSchema>;
