/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateConcessionSchemeDtoSchema = z.object({
    name: z.string().max(80),
    kind: z.enum(["WAIVER", "DISCOUNT", "SCHOLARSHIP", "BURSARY"]),
    calc: z.enum(["PERCENT", "FIXED"]),
    value: z.string().regex(/^-?\d+(\.\d+)?$/),
    categoryScope: z.array(z.string().uuid()).optional(),
    allowsStacking: z.boolean().optional(),
    glAccountId: z.string().uuid(),
});
export type CreateConcessionSchemeDto = z.infer<typeof CreateConcessionSchemeDtoSchema>;

export const UpdateConcessionSchemeDtoSchema = z.object({
    name: z.string().max(80).optional(),
    kind: z.enum(["WAIVER", "DISCOUNT", "SCHOLARSHIP", "BURSARY"]).optional(),
    calc: z.enum(["PERCENT", "FIXED"]).optional(),
    value: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    categoryScope: z.array(z.string().uuid()).optional(),
    allowsStacking: z.boolean().optional(),
    glAccountId: z.string().uuid().optional(),
});
export type UpdateConcessionSchemeDto = z.infer<typeof UpdateConcessionSchemeDtoSchema>;

export const ConcessionSchemeResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    kind: z.string(),
    calc: z.string(),
    value: z.string(),
    categoryScope: z.array(z.string()).nullable(),
    allowsStacking: z.boolean(),
    glAccountId: z.string(),
    isActive: z.boolean(),
});
export type ConcessionSchemeResponseDto = z.infer<typeof ConcessionSchemeResponseDtoSchema>;
