/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const RequestConcessionDtoSchema = z.object({
    kind: z.enum(["WAIVER", "DISCOUNT", "SCHOLARSHIP", "BURSARY"]),
    schemeId: z.string().uuid().optional(),
    studentId: z.string().uuid(),
    invoiceId: z.string().uuid().optional(),
    invoiceLineId: z.string().uuid().optional(),
    sponsorAwardId: z.string().uuid().optional(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    reason: z.string(),
});
export type RequestConcessionDto = z.infer<typeof RequestConcessionDtoSchema>;

export const DecideConcessionDtoSchema = z.object({
    approved: z.boolean(),
});
export type DecideConcessionDto = z.infer<typeof DecideConcessionDtoSchema>;

export const ConcessionResponseDtoSchema = z.object({
    id: z.string(),
    kind: z.string(),
    schemeId: z.string().nullable(),
    studentId: z.string(),
    invoiceId: z.string().nullable(),
    invoiceLineId: z.string().nullable(),
    sponsorAwardId: z.string().nullable(),
    amount: z.string(),
    reason: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
});
export type ConcessionResponseDto = z.infer<typeof ConcessionResponseDtoSchema>;
