/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateCreditNoteLineDtoSchema = z.object({
    feeCategoryId: z.string().uuid(),
    description: z.string().max(160).optional(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type CreateCreditNoteLineDto = z.infer<typeof CreateCreditNoteLineDtoSchema>;

export const CreateCreditNoteDtoSchema = z.object({
    invoiceId: z.string().uuid(),
    lines: z.array(CreateCreditNoteLineDtoSchema).min(1),
    reason: z.string(),
});
export type CreateCreditNoteDto = z.infer<typeof CreateCreditNoteDtoSchema>;

export const DecideCreditNoteDtoSchema = z.object({
    approved: z.boolean(),
});
export type DecideCreditNoteDto = z.infer<typeof DecideCreditNoteDtoSchema>;

export const CreditNoteResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    invoiceId: z.string(),
    reason: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
    total: z.string(),
});
export type CreditNoteResponseDto = z.infer<typeof CreditNoteResponseDtoSchema>;

export const CreditNoteLineResponseDtoSchema = z.object({
    id: z.string(),
    creditNoteId: z.string(),
    lineNo: z.number(),
    feeCategoryId: z.string(),
    description: z.string(),
    amount: z.string(),
});
export type CreditNoteLineResponseDto = z.infer<typeof CreditNoteLineResponseDtoSchema>;
