/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateDebitNoteLineDtoSchema = z.object({
    feeCategoryId: z.string().uuid(),
    description: z.string().max(160),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type CreateDebitNoteLineDto = z.infer<typeof CreateDebitNoteLineDtoSchema>;

export const CreateDebitNoteDtoSchema = z.object({
    studentId: z.string().uuid(),
    termId: z.string().uuid(),
    lines: z.array(CreateDebitNoteLineDtoSchema).min(1),
    reason: z.string(),
});
export type CreateDebitNoteDto = z.infer<typeof CreateDebitNoteDtoSchema>;

export const DebitNoteResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    studentId: z.string(),
    termId: z.string().nullable(),
    invoiceId: z.string().nullable(),
    reason: z.string(),
    status: z.string(),
    journalId: z.string().nullable(),
    total: z.string(),
});
export type DebitNoteResponseDto = z.infer<typeof DebitNoteResponseDtoSchema>;

export const DebitNoteLineResponseDtoSchema = z.object({
    id: z.string(),
    debitNoteId: z.string(),
    lineNo: z.number(),
    feeCategoryId: z.string(),
    description: z.string(),
    amount: z.string(),
});
export type DebitNoteLineResponseDto = z.infer<typeof DebitNoteLineResponseDtoSchema>;
