/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateFeeCategoryDtoSchema = z.object({
    name: z.string().max(60),
    glIncomeAccountId: z.string().uuid(),
    taxable: z.boolean().optional(),
    priority: z.number().min(0).int().optional(),
});
export type CreateFeeCategoryDto = z.infer<typeof CreateFeeCategoryDtoSchema>;

export const UpdateFeeCategoryDtoSchema = z.object({
    name: z.string().max(60).optional(),
    glIncomeAccountId: z.string().uuid().optional(),
    taxable: z.boolean().optional(),
    priority: z.number().min(0).int().optional(),
});
export type UpdateFeeCategoryDto = z.infer<typeof UpdateFeeCategoryDtoSchema>;

export const FeeCategoryResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    glIncomeAccountId: z.string(),
    taxable: z.boolean(),
    isActive: z.boolean(),
    priority: z.number(),
});
export type FeeCategoryResponseDto = z.infer<typeof FeeCategoryResponseDtoSchema>;
