/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateFeeStructureDtoSchema = z.object({
    academicYearId: z.string().uuid(),
    classId: z.string().uuid(),
    streamId: z.string().uuid().optional(),
    boarding: z.enum(["DAY", "BOARDER"]).optional(),
    feeGroupId: z.string().uuid().optional(),
});
export type CreateFeeStructureDto = z.infer<typeof CreateFeeStructureDtoSchema>;

export const CreateFeeStructureLineDtoSchema = z.object({
    feeCategoryId: z.string().uuid(),
    termId: z.string().uuid(),
    dueDate: z.string(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    isOptional: z.boolean().optional(),
});
export type CreateFeeStructureLineDto = z.infer<typeof CreateFeeStructureLineDtoSchema>;

export const UpdateFeeStructureLineDtoSchema = z.object({
    termId: z.string().uuid(),
    dueDate: z.string(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type UpdateFeeStructureLineDto = z.infer<typeof UpdateFeeStructureLineDtoSchema>;

export const FeeStructureResponseDtoSchema = z.object({
    id: z.string(),
    academicYearId: z.string(),
    classId: z.string(),
    streamId: z.string().nullable(),
    boarding: z.string().nullable(),
    feeGroupId: z.string().nullable(),
    version: z.number(),
    status: z.string(),
    publishedAt: z.coerce.date().nullable(),
    verificationToken: z.string().nullable(),
});
export type FeeStructureResponseDto = z.infer<typeof FeeStructureResponseDtoSchema>;

export const FeeStructureLineResponseDtoSchema = z.object({
    id: z.string(),
    feeStructureId: z.string(),
    feeCategoryId: z.string(),
    termId: z.string(),
    dueDate: z.string(),
    amount: z.string(),
    isOptional: z.boolean(),
});
export type FeeStructureLineResponseDto = z.infer<typeof FeeStructureLineResponseDtoSchema>;

export const FeeCategoryForScopeResponseDtoSchema = z.object({
    feeCategoryId: z.string(),
    name: z.string(),
    exampleAmount: z.string(),
});
export type FeeCategoryForScopeResponseDto = z.infer<typeof FeeCategoryForScopeResponseDtoSchema>;
