/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const GenerateInvoiceAdhocLineDtoSchema = z.object({
    feeCategoryId: z.string().uuid(),
    description: z.string().max(160),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type GenerateInvoiceAdhocLineDto = z.infer<typeof GenerateInvoiceAdhocLineDtoSchema>;

export const GenerateInvoiceDtoSchema = z.object({
    studentId: z.string().uuid(),
    termId: z.string().uuid(),
    source: z.enum(["STRUCTURE", "ADHOC", "RECURRING", "DEBIT_NOTE"]),
    adhocLines: z.array(GenerateInvoiceAdhocLineDtoSchema).min(1).optional(),
    issueDate: z.string().optional(),
    dueDate: z.string().optional(),
});
export type GenerateInvoiceDto = z.infer<typeof GenerateInvoiceDtoSchema>;

export const VoidInvoiceDtoSchema = z.object({
    reason: z.string(),
});
export type VoidInvoiceDto = z.infer<typeof VoidInvoiceDtoSchema>;

export const InvoiceResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    studentId: z.string(),
    termId: z.string(),
    feeStructureId: z.string().nullable(),
    issueDate: z.string(),
    dueDate: z.string(),
    status: z.string(),
    source: z.string(),
    subtotal: z.string(),
    concessionTotal: z.string(),
    total: z.string(),
    paidAmount: z.string(),
    balance: z.string(),
    journalId: z.string().nullable(),
});
export type InvoiceResponseDto = z.infer<typeof InvoiceResponseDtoSchema>;

export const PendingUpcomingInvoiceResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    dueDate: z.string(),
    total: z.string(),
    balance: z.string(),
    status: z.string(),
    studentId: z.string(),
    admissionNo: z.string(),
    studentName: z.string(),
    classId: z.string(),
});
export type PendingUpcomingInvoiceResponseDto = z.infer<typeof PendingUpcomingInvoiceResponseDtoSchema>;

export const PendingUpcomingInvoiceListResponseDtoSchema = z.object({
    items: z.array(PendingUpcomingInvoiceResponseDtoSchema),
    total: z.number(),
});
export type PendingUpcomingInvoiceListResponseDto = z.infer<typeof PendingUpcomingInvoiceListResponseDtoSchema>;

export const InvoiceLineResponseDtoSchema = z.object({
    id: z.string(),
    invoiceId: z.string(),
    lineNo: z.number(),
    feeCategoryId: z.string(),
    description: z.string(),
    amount: z.string(),
    concessionAmount: z.string(),
});
export type InvoiceLineResponseDto = z.infer<typeof InvoiceLineResponseDtoSchema>;
