/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const RunLateFeeBatchDtoSchema = z.object({
    policyId: z.string().uuid(),
    runDate: z.string(),
});
export type RunLateFeeBatchDto = z.infer<typeof RunLateFeeBatchDtoSchema>;

export const DecideLateFeeBatchDtoSchema = z.object({
    approved: z.boolean(),
});
export type DecideLateFeeBatchDto = z.infer<typeof DecideLateFeeBatchDtoSchema>;

export const LateFeeBatchResponseDtoSchema = z.object({
    id: z.string(),
    policyId: z.string(),
    runDate: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    summary: z.record(z.string(), z.unknown()),
});
export type LateFeeBatchResponseDto = z.infer<typeof LateFeeBatchResponseDtoSchema>;
