/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateLateFeePolicyDtoSchema = z.object({
    name: z.string().max(80),
    mode: z.enum(["FLAT", "PERCENT", "TIERED"]),
    params: z.record(z.string(), z.unknown()),
    graceDays: z.number().min(0).int().optional(),
    requiresApproval: z.boolean().optional(),
});
export type CreateLateFeePolicyDto = z.infer<typeof CreateLateFeePolicyDtoSchema>;

export const UpdateLateFeePolicyDtoSchema = z.object({
    mode: z.enum(["FLAT", "PERCENT", "TIERED"]).optional(),
    params: z.record(z.string(), z.unknown()).optional(),
    graceDays: z.number().min(0).int().optional(),
    requiresApproval: z.boolean().optional(),
});
export type UpdateLateFeePolicyDto = z.infer<typeof UpdateLateFeePolicyDtoSchema>;

export const LateFeePolicyResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    mode: z.string(),
    params: z.record(z.string(), z.unknown()),
    graceDays: z.number(),
    requiresApproval: z.boolean(),
    isActive: z.boolean(),
});
export type LateFeePolicyResponseDto = z.infer<typeof LateFeePolicyResponseDtoSchema>;
