/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateRefundVoucherDtoSchema = z.object({
    studentId: z.string().uuid(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    method: z.enum(["CASH", "BANK", "MPESA_B2C"]),
    payee: z.record(z.string(), z.unknown()),
});
export type CreateRefundVoucherDto = z.infer<typeof CreateRefundVoucherDtoSchema>;

export const DecideRefundVoucherDtoSchema = z.object({
    approved: z.boolean(),
});
export type DecideRefundVoucherDto = z.infer<typeof DecideRefundVoucherDtoSchema>;

export const MarkRefundVoucherPaidDtoSchema = z.object({
    b2cTransactionId: z.string().optional(),
});
export type MarkRefundVoucherPaidDto = z.infer<typeof MarkRefundVoucherPaidDtoSchema>;

export const RefundVoucherResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    studentId: z.string(),
    amount: z.string(),
    method: z.string(),
    payee: z.record(z.string(), z.unknown()),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
    b2cTransactionId: z.string().nullable(),
});
export type RefundVoucherResponseDto = z.infer<typeof RefundVoucherResponseDtoSchema>;
