/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateSponsorAwardDtoSchema = z.object({
    sponsorId: z.string().uuid(),
    studentId: z.string().uuid(),
    termId: z.string().uuid(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    categoryScope: z.array(z.string().uuid()).optional(),
});
export type CreateSponsorAwardDto = z.infer<typeof CreateSponsorAwardDtoSchema>;

export const UpdateSponsorAwardDtoSchema = z.object({
    amount: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    categoryScope: z.array(z.string().uuid()).optional(),
});
export type UpdateSponsorAwardDto = z.infer<typeof UpdateSponsorAwardDtoSchema>;

export const SponsorAwardResponseDtoSchema = z.object({
    id: z.string(),
    sponsorId: z.string(),
    studentId: z.string(),
    termId: z.string(),
    amount: z.string(),
    categoryScope: z.array(z.string()).nullable(),
    appliedAmount: z.string(),
});
export type SponsorAwardResponseDto = z.infer<typeof SponsorAwardResponseDtoSchema>;
