/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateStudentOptionalItemDtoSchema = z.object({
    studentId: z.string().uuid(),
    termId: z.string().uuid(),
    feeCategoryId: z.string().uuid(),
    amountOverride: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
});
export type CreateStudentOptionalItemDto = z.infer<typeof CreateStudentOptionalItemDtoSchema>;

export const UpdateStudentOptionalItemDtoSchema = z.object({
    amountOverride: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
});
export type UpdateStudentOptionalItemDto = z.infer<typeof UpdateStudentOptionalItemDtoSchema>;

export const StudentOptionalItemResponseDtoSchema = z.object({
    id: z.string(),
    studentId: z.string(),
    termId: z.string(),
    feeCategoryId: z.string(),
    amountOverride: z.string().nullable(),
});
export type StudentOptionalItemResponseDto = z.infer<typeof StudentOptionalItemResponseDtoSchema>;
