/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const PushEntityDtoSchema = z.object({
    kind: z.enum(["QUICKBOOKS", "XERO", "SAGE"]),
    entityType: z.enum(["INVOICE", "PAYMENT", "EXPENSE", "CUSTOMER"]),
    entityId: z.string().uuid(),
    payload: z.record(z.string(), z.unknown()),
});
export type PushEntityDto = z.infer<typeof PushEntityDtoSchema>;

export const TestConnectionDtoSchema = z.object({
    kind: z.enum(["QUICKBOOKS", "XERO", "SAGE"]),
});
export type TestConnectionDto = z.infer<typeof TestConnectionDtoSchema>;

export const TestConnectionResponseDtoSchema = z.object({
    ok: z.boolean(),
    message: z.string(),
});
export type TestConnectionResponseDto = z.infer<typeof TestConnectionResponseDtoSchema>;

export const SyncLogResponseDtoSchema = z.object({
    id: z.string(),
    kind: z.string(),
    direction: z.string(),
    entityType: z.string(),
    entityId: z.string(),
    status: z.string(),
    providerRef: z.string().nullable(),
    error: z.string().nullable(),
    at: z.string(),
});
export type SyncLogResponseDto = z.infer<typeof SyncLogResponseDtoSchema>;

export const ListSyncLogQueryDtoSchema = z.object({
    kind: z.enum(["QUICKBOOKS", "XERO", "SAGE"]).optional(),
    entityType: z.string().optional(),
    entityId: z.string().uuid().optional(),
    status: z.enum(["SUCCESS", "FAILED"]).optional(),
    page: z.number().min(1).int().optional(),
    pageSize: z.number().min(1).int().optional(),
});
export type ListSyncLogQueryDto = z.infer<typeof ListSyncLogQueryDtoSchema>;

export const ListSyncLogResponseDtoSchema = z.object({
    items: z.array(SyncLogResponseDtoSchema),
    meta: z.object({
    total: z.number(),
    page: z.number(),
    pageSize: z.number(),
    pageCount: z.number(),
  }),
});
export type ListSyncLogResponseDto = z.infer<typeof ListSyncLogResponseDtoSchema>;
