/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const ListWebhookDeliveriesQueryDtoSchema = z.object({
    subscriptionId: z.string().uuid().optional(),
    status: z.enum(["PENDING", "DELIVERED", "FAILED", "DEAD"]).optional(),
    page: z.number().min(1).int().optional(),
    pageSize: z.number().min(1).int().optional(),
});
export type ListWebhookDeliveriesQueryDto = z.infer<typeof ListWebhookDeliveriesQueryDtoSchema>;

export const WebhookDeliveryResponseDtoSchema = z.object({
    id: z.string(),
    subscriptionId: z.string(),
    eventType: z.string(),
    payload: z.record(z.string(), z.unknown()),
    attempt: z.number(),
    status: z.string(),
    responseCode: z.number().nullable(),
    nextRetryAt: z.string(),
    createdAt: z.string(),
});
export type WebhookDeliveryResponseDto = z.infer<typeof WebhookDeliveryResponseDtoSchema>;

export const ListWebhookDeliveriesResponseDtoSchema = z.object({
    items: z.array(WebhookDeliveryResponseDtoSchema),
    meta: z.object({
    total: z.number(),
    page: z.number(),
    pageSize: z.number(),
    pageCount: z.number(),
  }),
});
export type ListWebhookDeliveriesResponseDto = z.infer<typeof ListWebhookDeliveriesResponseDtoSchema>;

export const ProcessDueResponseDtoSchema = z.object({
    processed: z.number(),
    failed: z.number(),
});
export type ProcessDueResponseDto = z.infer<typeof ProcessDueResponseDtoSchema>;
