/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateWebhookSubscriptionDtoSchema = z.object({
    url: z.string().url().max(300),
    secret: z.string().min(8),
    events: z.array(z.string()).min(1),
    isActive: z.boolean().optional(),
});
export type CreateWebhookSubscriptionDto = z.infer<typeof CreateWebhookSubscriptionDtoSchema>;

export const UpdateWebhookSubscriptionDtoSchema = z.object({
    url: z.string().url().max(300).optional(),
    events: z.array(z.string()).min(1).optional(),
});
export type UpdateWebhookSubscriptionDto = z.infer<typeof UpdateWebhookSubscriptionDtoSchema>;

export const RotateWebhookSecretDtoSchema = z.object({
    secret: z.string().min(8),
});
export type RotateWebhookSecretDto = z.infer<typeof RotateWebhookSecretDtoSchema>;

export const DisableWebhookSubscriptionDtoSchema = z.object({
    reason: z.string().max(300),
});
export type DisableWebhookSubscriptionDto = z.infer<typeof DisableWebhookSubscriptionDtoSchema>;

export const WebhookSubscriptionResponseDtoSchema = z.object({
    id: z.string(),
    url: z.string(),
    events: z.array(z.string()),
    isActive: z.boolean(),
    disabledReason: z.string().nullable(),
    failureStreakStartedAt: z.string().nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
});
export type WebhookSubscriptionResponseDto = z.infer<typeof WebhookSubscriptionResponseDtoSchema>;
