/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const ListMessagesQueryDtoSchema = z.object({
    status: z.enum(["QUEUED", "SENT", "DELIVERED", "FAILED", "OPTED_OUT"]).optional(),
    entityType: z.string().optional(),
    entityId: z.string().uuid().optional(),
    broadcastId: z.string().uuid().optional(),
    page: z.number().min(1).int().optional(),
    pageSize: z.number().min(1).int().optional(),
});
export type ListMessagesQueryDto = z.infer<typeof ListMessagesQueryDtoSchema>;
