/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const MessageResponseDtoSchema = z.object({
    id: z.string(),
    channel: z.enum(["SMS", "EMAIL", "PUSH", "WHATSAPP", "INAPP"]),
    recipient: z.string(),
    templateEvent: z.string().nullable(),
    broadcastId: z.string().nullable(),
    entityType: z.string().nullable(),
    entityId: z.string().nullable(),
    bodyRendered: z.string(),
    status: z.enum(["QUEUED", "SENT", "DELIVERED", "FAILED", "OPTED_OUT"]),
    provider: z.string().nullable(),
    providerRef: z.string().nullable(),
    costAmount: z.string().nullable(),
    segments: z.number().nullable(),
    error: z.string().nullable(),
    queuedAt: z.coerce.date(),
    sentAt: z.coerce.date().nullable(),
    deliveredAt: z.coerce.date().nullable(),
});
export type MessageResponseDto = z.infer<typeof MessageResponseDtoSchema>;
