/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const TemplateResponseDtoSchema = z.object({
    id: z.string(),
    eventCode: z.string(),
    channel: z.enum(["SMS", "EMAIL", "PUSH", "WHATSAPP", "INAPP"]),
    locale: z.string(),
    subject: z.string().nullable(),
    body: z.string(),
    variables: z.unknown(),
    isActive: z.boolean(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    version: z.number(),
});
export type TemplateResponseDto = z.infer<typeof TemplateResponseDtoSchema>;
