/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateUserDtoSchema = z.object({
    username: z.string().max(60).min(3),
    email: z.string().email().max(160).optional(),
    phone: z.string().regex(/^\+\d{6,19}$/).optional(),
    fullName: z.string().max(120),
    userType: z.enum(["STAFF", "PARENT", "SYSTEM"]).optional(),
    departmentId: z.string().uuid().optional(),
    locale: z.string().max(8).optional(),
});
export type CreateUserDto = z.infer<typeof CreateUserDtoSchema>;
