/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const RoleResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string().nullable(),
    isSystemTemplate: z.boolean(),
    isAuditorClass: z.boolean(),
});
export type RoleResponseDto = z.infer<typeof RoleResponseDtoSchema>;

export const AssignRoleResultDtoSchema = z.object({
    userId: z.string(),
    roleId: z.string(),
    assigned: z.boolean(),
});
export type AssignRoleResultDto = z.infer<typeof AssignRoleResultDtoSchema>;
