/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const UserResponseDtoSchema = z.object({
    id: z.string(),
    username: z.string(),
    email: z.string().nullable(),
    phone: z.string().nullable(),
    fullName: z.string(),
    status: z.enum(["INVITED", "ACTIVE", "SUSPENDED", "DEACTIVATED"]),
    userType: z.enum(["STAFF", "PARENT", "SYSTEM"]),
    mustChangePassword: z.boolean(),
    twofaEnabled: z.boolean(),
    departmentId: z.string().nullable(),
    departmentName: z.string().nullable(),
    authorityLimitAmount: z.string().nullable(),
    lastLoginAt: z.string().nullable(),
    passwordChangedAt: z.string(),
    locale: z.string(),
});
export type UserResponseDto = z.infer<typeof UserResponseDtoSchema>;

export const CreateUserResponseDtoSchema = z.object({
    user: UserResponseDtoSchema,
    temporaryPassword: z.string(),
});
export type CreateUserResponseDto = z.infer<typeof CreateUserResponseDtoSchema>;

export const UserListResponseDtoSchema = z.object({
    items: z.array(UserResponseDtoSchema),
    total: z.number(),
});
export type UserListResponseDto = z.infer<typeof UserListResponseDtoSchema>;
