/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const AccountResponseDtoSchema = z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    class: z.string(),
    parentId: z.string().nullable(),
    isPostable: z.boolean(),
    isControl: z.boolean(),
    controlDomain: z.string().nullable(),
    isActive: z.boolean(),
    taxTreatment: z.string().nullable(),
});
export type AccountResponseDto = z.infer<typeof AccountResponseDtoSchema>;

export interface AccountTreeNodeResponseDto extends AccountResponseDto {
  children: AccountTreeNodeResponseDto[];
}
export const AccountTreeNodeResponseDtoSchema: z.ZodType<AccountTreeNodeResponseDto> = AccountResponseDtoSchema.merge(z.object({
    children: z.array(z.lazy(() => AccountTreeNodeResponseDtoSchema)),
}));
