/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const BudgetResponseDtoSchema = z.object({
    id: z.string(),
    fiscalYearId: z.string(),
    name: z.string(),
    versionLabel: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
});
export type BudgetResponseDto = z.infer<typeof BudgetResponseDtoSchema>;

export const BudgetLineResponseDtoSchema = z.object({
    id: z.string(),
    budgetId: z.string(),
    accountId: z.string(),
    costCenterId: z.string().nullable(),
    periodPhasing: z.record(z.string(), z.unknown()),
    annualAmount: z.string(),
});
export type BudgetLineResponseDto = z.infer<typeof BudgetLineResponseDtoSchema>;
