/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";
import { BudgetLineInputDtoSchema } from "./budget-line-input.schema";

export const CreateBudgetDtoSchema = z.object({
    fiscalYearId: z.string().uuid(),
    name: z.string().max(80),
    versionLabel: z.string().max(20),
    lines: z.array(BudgetLineInputDtoSchema).min(1),
});
export type CreateBudgetDto = z.infer<typeof CreateBudgetDtoSchema>;
