/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const JournalLineResponseDtoSchema = z.object({
    id: z.string(),
    journalId: z.string(),
    lineNo: z.number(),
    accountId: z.string(),
    costCenterId: z.string().nullable(),
    debit: z.string(),
    credit: z.string(),
    memo: z.string().nullable(),
    entityRefType: z.string().nullable(),
    entityRefId: z.string().nullable(),
});
export type JournalLineResponseDto = z.infer<typeof JournalLineResponseDtoSchema>;

export const JournalResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    journalDate: z.string(),
    periodId: z.string(),
    sourceModule: z.string(),
    sourceDocType: z.string(),
    sourceDocId: z.string(),
    narration: z.string(),
    journalType: z.string(),
    reversalOfId: z.string().nullable(),
    approvalRef: z.string().nullable(),
    postedBy: z.string(),
    postedAt: z.coerce.date(),
    lines: z.array(JournalLineResponseDtoSchema).optional(),
});
export type JournalResponseDto = z.infer<typeof JournalResponseDtoSchema>;
