/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const JournalLineInputDtoSchema = z.object({
    accountId: z.string().uuid(),
    costCenterId: z.string().uuid().optional(),
    debit: z.string().regex(/^-?\d+(\.\d+)?$/),
    credit: z.string().regex(/^-?\d+(\.\d+)?$/),
    memo: z.string().max(200).optional(),
    entityRefType: z.string().max(30).optional(),
    entityRefId: z.string().uuid().optional(),
});
export type JournalLineInputDto = z.infer<typeof JournalLineInputDtoSchema>;
