/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";
import { JournalLineInputDtoSchema } from "./journal-line-input.schema";

export const PostJournalDtoSchema = z.object({
    journalDate: z.string(),
    sourceModule: z.string().max(20),
    sourceDocType: z.string().max(30).optional(),
    sourceDocId: z.string().uuid().optional(),
    narration: z.string(),
    periodId: z.string().uuid().optional(),
    lines: z.array(JournalLineInputDtoSchema).min(1),
});
export type PostJournalDto = z.infer<typeof PostJournalDtoSchema>;
