/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const UpdateAccountDtoSchema = z.object({
    name: z.string().max(120).optional(),
    isControl: z.boolean().optional(),
    controlDomain: z.enum(["AR_STUDENT", "AR_SPONSOR", "AP_SUPPLIER", "WALLET", "INVENTORY", "PAYROLL", "PREPAYMENT", "MPESA_CLEARING", "TRANSFER_CLEARING"]).nullable().optional(),
    taxTreatment: z.string().max(20).nullable().optional(),
});
export type UpdateAccountDto = z.infer<typeof UpdateAccountDtoSchema>;
