/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreatePyrlComponentDtoSchema = z.object({
    code: z.string().max(20),
    name: z.string().max(120),
    kind: z.string(),
    isTaxable: z.boolean(),
    isStatutory: z.boolean().optional(),
    glAccountId: z.string().uuid(),
});
export type CreatePyrlComponentDto = z.infer<typeof CreatePyrlComponentDtoSchema>;

export const UpdatePyrlComponentDtoSchema = z.object({
    name: z.string().max(120).optional(),
    isTaxable: z.boolean().optional(),
    isStatutory: z.boolean().optional(),
    glAccountId: z.string().uuid().optional(),
});
export type UpdatePyrlComponentDto = z.infer<typeof UpdatePyrlComponentDtoSchema>;

export const PyrlComponentResponseDtoSchema = z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    kind: z.enum(["EARNING", "DEDUCTION"]),
    isTaxable: z.boolean(),
    isStatutory: z.boolean(),
    glAccountId: z.string(),
});
export type PyrlComponentResponseDto = z.infer<typeof PyrlComponentResponseDtoSchema>;
