/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const AddEmployeeComponentDtoSchema = z.object({
    employeeId: z.string().uuid(),
    componentId: z.string().uuid(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    effectiveFrom: z.string(),
    effectiveTo: z.string().optional(),
});
export type AddEmployeeComponentDto = z.infer<typeof AddEmployeeComponentDtoSchema>;

export const EndEmployeeComponentDtoSchema = z.object({
    componentId: z.string().uuid(),
    effectiveTo: z.string(),
});
export type EndEmployeeComponentDto = z.infer<typeof EndEmployeeComponentDtoSchema>;

export const PyrlEmployeeComponentResponseDtoSchema = z.object({
    id: z.string(),
    employeeId: z.string(),
    componentId: z.string(),
    amount: z.string(),
    effectiveFrom: z.string(),
    effectiveTo: z.string().nullable(),
});
export type PyrlEmployeeComponentResponseDto = z.infer<typeof PyrlEmployeeComponentResponseDtoSchema>;
