/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreatePyrlEmployeeDtoSchema = z.object({
    staffNo: z.string().max(20),
    userId: z.string().uuid().optional(),
    fullName: z.string().max(120),
    nationalId: z.string().max(20),
    kraPin: z.string().max(15),
    nssfNo: z.string().max(20).optional(),
    shifNo: z.string().max(20).optional(),
    employmentType: z.string(),
    departmentId: z.string().uuid(),
    jobTitle: z.string().max(80),
    hireDate: z.string(),
    costCenterId: z.string().uuid(),
    payDetails: z.unknown().optional(),
    bankName: z.unknown().optional(),
    branch: z.unknown().optional(),
    account: z.unknown().optional(),
});
export type CreatePyrlEmployeeDto = z.infer<typeof CreatePyrlEmployeeDtoSchema>;

export const UpdatePyrlEmployeeDtoSchema = z.object({
    fullName: z.string().max(120).optional(),
    jobTitle: z.string().max(80).optional(),
    departmentId: z.string().uuid().optional(),
    costCenterId: z.string().uuid().optional(),
    employmentType: z.string().optional(),
    nssfNo: z.string().max(20).nullable().optional(),
    shifNo: z.string().max(20).nullable().optional(),
    userId: z.string().uuid().nullable().optional(),
    payDetails: z.unknown().optional(),
    bankName: z.unknown().optional(),
    branch: z.unknown().optional(),
    account: z.unknown().optional(),
});
export type UpdatePyrlEmployeeDto = z.infer<typeof UpdatePyrlEmployeeDtoSchema>;

export const ExitPyrlEmployeeDtoSchema = z.object({
    exitDate: z.string(),
});
export type ExitPyrlEmployeeDto = z.infer<typeof ExitPyrlEmployeeDtoSchema>;

export const PyrlEmployeeResponseDtoSchema = z.object({
    id: z.string(),
    staffNo: z.string(),
    userId: z.string().nullable(),
    fullName: z.string(),
    nationalId: z.string(),
    kraPin: z.string(),
    nssfNo: z.string().nullable(),
    shifNo: z.string().nullable(),
    employmentType: z.enum(["PERMANENT", "CONTRACT", "CASUAL", "PART_TIME"]),
    departmentId: z.string(),
    jobTitle: z.string(),
    hireDate: z.string(),
    exitDate: z.string().nullable(),
    payDetails: z.unknown().nullable(),
    bankName: z.unknown().nullable(),
    branch: z.unknown().nullable(),
    account: z.unknown().nullable(),
    costCenterId: z.string(),
    isActive: z.boolean(),
});
export type PyrlEmployeeResponseDto = z.infer<typeof PyrlEmployeeResponseDtoSchema>;

export const SearchPyrlEmployeeQueryDtoSchema = z.object({
    q: z.string(),
});
export type SearchPyrlEmployeeQueryDto = z.infer<typeof SearchPyrlEmployeeQueryDtoSchema>;
