/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const AssignEmployeeDtoSchema = z.object({
    employeeId: z.string().uuid(),
    structureId: z.string().uuid(),
    basicPay: z.string().regex(/^-?\d+(\.\d+)?$/),
    effectiveFrom: z.string(),
    effectiveTo: z.string().optional(),
});
export type AssignEmployeeDto = z.infer<typeof AssignEmployeeDtoSchema>;

export const EndAssignmentDtoSchema = z.object({
    effectiveTo: z.string(),
});
export type EndAssignmentDto = z.infer<typeof EndAssignmentDtoSchema>;

export const PyrlEmployeeAssignmentResponseDtoSchema = z.object({
    id: z.string(),
    employeeId: z.string(),
    structureId: z.string(),
    basicPay: z.string(),
    effectiveFrom: z.string(),
    effectiveTo: z.string().nullable(),
});
export type PyrlEmployeeAssignmentResponseDto = z.infer<typeof PyrlEmployeeAssignmentResponseDtoSchema>;
