/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreatePyrlLoanDtoSchema = z.object({
    employeeId: z.string().uuid(),
    principal: z.string().regex(/^-?\d+(\.\d+)?$/),
    rate: z.string().regex(/^-?\d+(\.\d+)?$/),
    rateKind: z.enum(["FLAT", "REDUCING"]),
    termMonths: z.number().min(1).int(),
});
export type CreatePyrlLoanDto = z.infer<typeof CreatePyrlLoanDtoSchema>;

export const DecidePyrlLoanDtoSchema = z.object({
    approved: z.boolean(),
});
export type DecidePyrlLoanDto = z.infer<typeof DecidePyrlLoanDtoSchema>;

export const RecordLoanRecoveryDtoSchema = z.object({
    periodKey: z.string(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type RecordLoanRecoveryDto = z.infer<typeof RecordLoanRecoveryDtoSchema>;

export const SettleLoanEarlyDtoSchema = z.object({
    settlementDate: z.string(),
});
export type SettleLoanEarlyDto = z.infer<typeof SettleLoanEarlyDtoSchema>;

export const PyrlLoanResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    employeeId: z.string(),
    principal: z.string(),
    rate: z.string(),
    rateKind: z.enum(["FLAT", "REDUCING"]),
    termMonths: z.number(),
    status: z.enum(["PENDING_APPROVAL", "ACTIVE", "SETTLED", "WRITTEN_OFF"]),
    approvalRef: z.string().nullable(),
    balance: z.string(),
});
export type PyrlLoanResponseDto = z.infer<typeof PyrlLoanResponseDtoSchema>;

export const PyrlLoanScheduleResponseDtoSchema = z.object({
    id: z.string(),
    loanId: z.string(),
    seq: z.number(),
    duePeriod: z.string(),
    principalDue: z.string(),
    interestDue: z.string(),
    recoveredAmount: z.string(),
});
export type PyrlLoanScheduleResponseDto = z.infer<typeof PyrlLoanScheduleResponseDtoSchema>;
