/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreatePyrlOneoffDtoSchema = z.object({
    employeeId: z.string().uuid(),
    periodKey: z.string(),
    kind: z.enum(["EARNING", "DEDUCTION"]),
    componentId: z.string().uuid(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    reason: z.string(),
});
export type CreatePyrlOneoffDto = z.infer<typeof CreatePyrlOneoffDtoSchema>;

export const UpdatePyrlOneoffDtoSchema = z.object({
    amount: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    reason: z.string().optional(),
});
export type UpdatePyrlOneoffDto = z.infer<typeof UpdatePyrlOneoffDtoSchema>;

export const PyrlOneoffResponseDtoSchema = z.object({
    id: z.string(),
    employeeId: z.string(),
    periodKey: z.string(),
    kind: z.enum(["EARNING", "DEDUCTION"]),
    componentId: z.string(),
    amount: z.string(),
    reason: z.string(),
    approvalRef: z.string().nullable(),
});
export type PyrlOneoffResponseDto = z.infer<typeof PyrlOneoffResponseDtoSchema>;
