/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreatePyrlRunDtoSchema = z.object({
    periodKey: z.string(),
    runKind: z.enum(["MAIN", "SUPPLEMENTARY"]),
    supplementsRunId: z.string().uuid().optional(),
});
export type CreatePyrlRunDto = z.infer<typeof CreatePyrlRunDtoSchema>;

export const DecidePyrlRunDtoSchema = z.object({
    approved: z.boolean(),
});
export type DecidePyrlRunDto = z.infer<typeof DecidePyrlRunDtoSchema>;

export const PayPyrlRunDtoSchema = z.object({
    method: z.enum(["BANK", "MPESA_B2C", "CASH"]),
});
export type PayPyrlRunDto = z.infer<typeof PayPyrlRunDtoSchema>;

export const PyrlRunTotalsResponseDtoSchema = z.object({
    employeeCount: z.number(),
    totalGross: z.string(),
    totalTaxable: z.string(),
    totalPaye: z.string(),
    totalNssfEmployee: z.string(),
    totalNssfEmployer: z.string(),
    totalShif: z.string(),
    totalAhlEmployee: z.string(),
    totalAhlEmployer: z.string(),
    totalLoanRecovered: z.string(),
    totalOtherDeductions: z.string(),
    totalNetPay: z.string(),
});
export type PyrlRunTotalsResponseDto = z.infer<typeof PyrlRunTotalsResponseDtoSchema>;

export const PyrlRunResponseDtoSchema = z.object({
    id: z.string(),
    periodKey: z.string(),
    runKind: z.enum(["MAIN", "SUPPLEMENTARY"]),
    supplementsRunId: z.string().nullable(),
    status: z.enum(["DRAFT", "COMPUTED", "REVIEW", "PENDING_APPROVAL", "APPROVED", "COMMITTED", "PAID", "FILED"]),
    initiatedBy: z.string(),
    approvedBy: z.string().nullable(),
    committedAt: z.coerce.date().nullable(),
    journalId: z.string().nullable(),
    totals: z.record(z.string(), z.unknown()),
    varianceReport: z.record(z.string(), z.unknown()).nullable(),
});
export type PyrlRunResponseDto = z.infer<typeof PyrlRunResponseDtoSchema>;

export const PyrlRunLineResponseDtoSchema = z.object({
    id: z.string(),
    runId: z.string(),
    employeeId: z.string(),
    gross: z.string(),
    taxable: z.string(),
    paye: z.string(),
    nssfEmployee: z.string(),
    nssfEmployer: z.string(),
    shif: z.string(),
    ahlEmployee: z.string(),
    ahlEmployer: z.string(),
    loanRecovered: z.string(),
    otherDeductions: z.string(),
    netPay: z.string(),
    deferredRecovery: z.string(),
    payslipFileId: z.string().nullable(),
    paidVia: z.enum(["BANK", "MPESA_B2C", "CASH"]).nullable(),
    paidAt: z.coerce.date().nullable(),
});
export type PyrlRunLineResponseDto = z.infer<typeof PyrlRunLineResponseDtoSchema>;

export const PyrlRunLineComponentResponseDtoSchema = z.object({
    id: z.string(),
    runLineId: z.string(),
    componentId: z.string(),
    amount: z.string(),
});
export type PyrlRunLineComponentResponseDto = z.infer<typeof PyrlRunLineComponentResponseDtoSchema>;
