/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreatePyrlSalaryStructureDtoSchema = z.object({
    name: z.string().max(120),
    grade: z.string().max(30).optional(),
    effectiveFrom: z.string(),
});
export type CreatePyrlSalaryStructureDto = z.infer<typeof CreatePyrlSalaryStructureDtoSchema>;

export const UpdatePyrlSalaryStructureDtoSchema = z.object({
    name: z.string().max(120).optional(),
    grade: z.string().max(30).optional(),
    effectiveFrom: z.string().optional(),
});
export type UpdatePyrlSalaryStructureDto = z.infer<typeof UpdatePyrlSalaryStructureDtoSchema>;

export const PyrlSalaryStructureResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    grade: z.string().nullable(),
    effectiveFrom: z.string(),
});
export type PyrlSalaryStructureResponseDto = z.infer<typeof PyrlSalaryStructureResponseDtoSchema>;

export const StructureComponentLineDtoSchema = z.object({
    componentId: z.string().uuid(),
    type: z.enum(["FIXED", "PERCENT_OF_BASIC"]),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    rate: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
});
export type StructureComponentLineDto = z.infer<typeof StructureComponentLineDtoSchema>;

export const StructureComponentLineResponseDtoSchema = z.object({
    id: z.string(),
    structureId: z.string(),
    componentId: z.string(),
    amount: z.string().nullable(),
    formula: z.record(z.string(), z.unknown()).nullable(),
});
export type StructureComponentLineResponseDto = z.infer<typeof StructureComponentLineResponseDtoSchema>;
