/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreatePyrlStatutoryTableDtoSchema = z.object({
    kind: z.string(),
    effectiveFrom: z.string(),
    params: z.record(z.string(), z.unknown()),
    sourceNote: z.string(),
});
export type CreatePyrlStatutoryTableDto = z.infer<typeof CreatePyrlStatutoryTableDtoSchema>;

export const UpdatePyrlStatutoryTableDtoSchema = z.object({
    params: z.record(z.string(), z.unknown()).optional(),
    sourceNote: z.string().optional(),
});
export type UpdatePyrlStatutoryTableDto = z.infer<typeof UpdatePyrlStatutoryTableDtoSchema>;

export const PyrlStatutoryTableResponseDtoSchema = z.object({
    id: z.string(),
    kind: z.enum(["PAYE", "NSSF", "SHIF", "AHL"]),
    effectiveFrom: z.string(),
    params: z.record(z.string(), z.unknown()),
    sourceNote: z.string(),
});
export type PyrlStatutoryTableResponseDto = z.infer<typeof PyrlStatutoryTableResponseDtoSchema>;
