/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateItemDtoSchema = z.object({
    code: z.string(),
    name: z.string(),
    categoryId: z.string().uuid(),
    uom: z.string(),
    uomConversions: z.record(z.string(), z.unknown()).optional(),
    barcode: z.string().optional(),
    itemType: z.enum(["STOCK", "CONSUMABLE", "SERVICE", "RESALE"]),
    reorderLevel: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    reorderQty: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    preferredSupplierIds: z.array(z.string().uuid()).optional(),
    glAssetAccountId: z.string().uuid(),
    glExpenseAccountId: z.string().uuid(),
    glIncomeAccountId: z.string().uuid().optional(),
    salePrice: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
});
export type CreateItemDto = z.infer<typeof CreateItemDtoSchema>;

export const UpdateItemDtoSchema = z.object({
    name: z.string().optional(),
    categoryId: z.string().uuid().optional(),
    uom: z.string().optional(),
    uomConversions: z.record(z.string(), z.unknown()).optional(),
    barcode: z.string().optional(),
    itemType: z.enum(["STOCK", "CONSUMABLE", "SERVICE", "RESALE"]).optional(),
    reorderLevel: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    reorderQty: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    preferredSupplierIds: z.array(z.string().uuid()).optional(),
    glAssetAccountId: z.string().uuid().optional(),
    glExpenseAccountId: z.string().uuid().optional(),
    glIncomeAccountId: z.string().uuid().optional(),
    salePrice: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    isActive: z.boolean().optional(),
});
export type UpdateItemDto = z.infer<typeof UpdateItemDtoSchema>;

export const ItemResponseDtoSchema = z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    categoryId: z.string(),
    uom: z.string(),
    barcode: z.string().nullable(),
    itemType: z.string(),
    reorderLevel: z.string().nullable(),
    reorderQty: z.string().nullable(),
    glAssetAccountId: z.string(),
    glExpenseAccountId: z.string(),
    glIncomeAccountId: z.string().nullable(),
    salePrice: z.string().nullable(),
    avgCost: z.string(),
    isActive: z.boolean(),
});
export type ItemResponseDto = z.infer<typeof ItemResponseDtoSchema>;
