/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const IssueStockDtoSchema = z.object({
    itemId: z.string().uuid(),
    storeId: z.string().uuid(),
    qty: z.string().regex(/^-?\d+(\.\d+)?$/),
    departmentId: z.string().uuid().optional(),
    refDocType: z.string().optional(),
    refDocId: z.string().uuid().optional(),
});
export type IssueStockDto = z.infer<typeof IssueStockDtoSchema>;

export const StockBalanceResponseDtoSchema = z.object({
    itemId: z.string(),
    storeId: z.string(),
    qty: z.string(),
    value: z.string(),
});
export type StockBalanceResponseDto = z.infer<typeof StockBalanceResponseDtoSchema>;

export const MovementResponseDtoSchema = z.object({
    id: z.string(),
    itemId: z.string(),
    storeId: z.string(),
    movementType: z.string(),
    qty: z.string(),
    unitCost: z.string(),
    value: z.string(),
    refDocType: z.string(),
    refDocId: z.string(),
    departmentId: z.string().nullable(),
    journalId: z.string().nullable(),
    at: z.coerce.date(),
});
export type MovementResponseDto = z.infer<typeof MovementResponseDtoSchema>;
