/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const StockTakeScopeDtoSchema = z.object({
    itemIds: z.union([z.array(z.string()), z.literal("ALL")]),
});
export type StockTakeScopeDto = z.infer<typeof StockTakeScopeDtoSchema>;

export const CreateStockTakeDtoSchema = z.object({
    storeId: z.string().uuid(),
    scope: StockTakeScopeDtoSchema,
});
export type CreateStockTakeDto = z.infer<typeof CreateStockTakeDtoSchema>;

export const RecordCountDtoSchema = z.object({
    lineId: z.string().uuid(),
    countedQty: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type RecordCountDto = z.infer<typeof RecordCountDtoSchema>;

export const RecordCountsDtoSchema = z.object({
    counts: z.array(RecordCountDtoSchema).min(1),
});
export type RecordCountsDto = z.infer<typeof RecordCountsDtoSchema>;

export const DecideStockTakeDtoSchema = z.object({
    decision: z.string(),
});
export type DecideStockTakeDto = z.infer<typeof DecideStockTakeDtoSchema>;

export const StockTakeResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    storeId: z.string(),
    scope: z.record(z.string(), z.unknown()),
    snapshotAt: z.coerce.date(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
});
export type StockTakeResponseDto = z.infer<typeof StockTakeResponseDtoSchema>;

export const StockTakeLineResponseDtoSchema = z.object({
    id: z.string(),
    stockTakeId: z.string(),
    itemId: z.string(),
    snapshotQty: z.string(),
    countedQty: z.string().nullable(),
    varianceQty: z.string().nullable(),
    varianceValue: z.string().nullable().optional(),
});
export type StockTakeLineResponseDto = z.infer<typeof StockTakeLineResponseDtoSchema>;
