/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateStoreDtoSchema = z.object({
    name: z.string(),
    location: z.string(),
    keeperUserId: z.string().uuid(),
});
export type CreateStoreDto = z.infer<typeof CreateStoreDtoSchema>;

export const UpdateStoreDtoSchema = z.object({
    name: z.string().optional(),
    location: z.string().optional(),
    keeperUserId: z.string().uuid().optional(),
    isActive: z.boolean().optional(),
});
export type UpdateStoreDto = z.infer<typeof UpdateStoreDtoSchema>;

export const StoreResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    location: z.string(),
    keeperUserId: z.string(),
    isActive: z.boolean(),
});
export type StoreResponseDto = z.infer<typeof StoreResponseDtoSchema>;
