/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const IssueTransferLineDtoSchema = z.object({
    itemId: z.string().uuid(),
    qty: z.string().regex(/^-?\d+(\.\d+)?$/),
    unitCost: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type IssueTransferLineDto = z.infer<typeof IssueTransferLineDtoSchema>;

export const IssueTransferDtoSchema = z.object({
    fromStoreId: z.string().uuid(),
    toStoreId: z.string().uuid(),
    lines: z.array(IssueTransferLineDtoSchema).min(1),
});
export type IssueTransferDto = z.infer<typeof IssueTransferDtoSchema>;

export const TransferResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    fromStoreId: z.string(),
    toStoreId: z.string(),
    status: z.string(),
    issuedBy: z.string(),
    receivedBy: z.string().nullable(),
});
export type TransferResponseDto = z.infer<typeof TransferResponseDtoSchema>;

export const TransferLineResponseDtoSchema = z.object({
    id: z.string(),
    transferId: z.string(),
    lineNo: z.number(),
    itemId: z.string(),
    qty: z.string(),
    unitCost: z.string(),
});
export type TransferLineResponseDto = z.infer<typeof TransferLineResponseDtoSchema>;
