/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const InstanceResponseDtoSchema = z.object({
    id: z.string(),
    workflowVersionId: z.string(),
    domainCode: z.string(),
    entityType: z.string(),
    entityId: z.string(),
    amount: z.string().nullable(),
    initiatorId: z.string(),
    status: z.enum(["PENDING", "APPROVED", "REJECTED", "RETURNED", "CANCELLED"]),
    currentLevel: z.number(),
    submittedAt: z.coerce.date(),
    decidedAt: z.coerce.date().nullable(),
});
export type InstanceResponseDto = z.infer<typeof InstanceResponseDtoSchema>;
