/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const LevelResponseDtoSchema = z.object({
    id: z.string(),
    workflowVersionId: z.string(),
    seq: z.number(),
    approverType: z.enum(["ROLE", "USERS", "DEPT_HEAD"]),
    roleId: z.string().nullable(),
    userIds: z.array(z.string()).nullable(),
    mode: z.enum(["SEQUENTIAL", "PARALLEL"]),
    quorum: z.number(),
    slaHours: z.number().nullable(),
    escalation: z.record(z.string(), z.unknown()).nullable(),
});
export type LevelResponseDto = z.infer<typeof LevelResponseDtoSchema>;
