/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const LevelInputDtoSchema = z.object({
    seq: z.number().min(1).int(),
    approverType: z.enum(["ROLE", "USERS", "DEPT_HEAD"]),
    roleId: z.string().uuid().optional(),
    userIds: z.array(z.string().uuid()).min(1).optional(),
    mode: z.enum(["SEQUENTIAL", "PARALLEL"]),
    quorum: z.number().min(1).int().optional(),
    slaHours: z.number().min(1).int().optional(),
    escalation: z.record(z.string(), z.unknown()).optional(),
});
export type LevelInputDto = z.infer<typeof LevelInputDtoSchema>;
