/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";
import { LevelInputDtoSchema } from "./level-input.schema";
import { RoutingRuleInputDtoSchema } from "./routing-rule-input.schema";

export const PublishWorkflowVersionDtoSchema = z.object({
    levels: z.array(LevelInputDtoSchema).min(1),
    routingRules: z.array(RoutingRuleInputDtoSchema),
});
export type PublishWorkflowVersionDto = z.infer<typeof PublishWorkflowVersionDtoSchema>;
