/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateServicePointDtoSchema = z.object({
    name: z.string(),
    type: z.enum(["TRANSPORT", "LIBRARY", "SHOP", "MEALS", "PRINTING", "TRIPS", "ACTIVITIES", "EMERGENCY", "CUSTOM"]),
    glIncomeAccountId: z.string().uuid(),
    perTxnLimit: z.string().regex(/^\d+(\.\d{1,4})?$/).optional(),
});
export type CreateServicePointDto = z.infer<typeof CreateServicePointDtoSchema>;

export const UpdateServicePointDtoSchema = z.object({
    name: z.string().optional(),
    perTxnLimit: z.string().regex(/^\d+(\.\d{1,4})?$/).optional(),
    isActive: z.boolean().optional(),
});
export type UpdateServicePointDto = z.infer<typeof UpdateServicePointDtoSchema>;

export const AssignOperatorDtoSchema = z.object({
    userId: z.string().uuid(),
});
export type AssignOperatorDto = z.infer<typeof AssignOperatorDtoSchema>;

export const ServicePointResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    type: z.string(),
    glIncomeAccountId: z.string(),
    isActive: z.boolean(),
    perTxnLimit: z.string().nullable(),
});
export type ServicePointResponseDto = z.infer<typeof ServicePointResponseDtoSchema>;

export const ServicePointOperatorResponseDtoSchema = z.object({
    id: z.string(),
    servicePointId: z.string(),
    userId: z.string(),
});
export type ServicePointOperatorResponseDto = z.infer<typeof ServicePointOperatorResponseDtoSchema>;
