/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const UpdateWalletLimitsDtoSchema = z.object({
    dailyLimit: z.string().regex(/^\d+(\.\d{1,4})?$/).nullable().optional(),
    txnLimit: z.string().regex(/^\d+(\.\d{1,4})?$/).nullable().optional(),
    categoryBlocks: z.array(z.enum(["TRANSPORT", "LIBRARY", "SHOP", "MEALS", "PRINTING", "TRIPS", "ACTIVITIES", "EMERGENCY", "CUSTOM"])).optional(),
});
export type UpdateWalletLimitsDto = z.infer<typeof UpdateWalletLimitsDtoSchema>;

export const SetWalletStatusDtoSchema = z.object({
    status: z.enum(["ACTIVE", "LOCKED", "FROZEN"]),
    reason: z.string().optional(),
});
export type SetWalletStatusDto = z.infer<typeof SetWalletStatusDtoSchema>;

export const WalletResponseDtoSchema = z.object({
    id: z.string(),
    studentId: z.string(),
    status: z.string(),
    balance: z.string(),
    overdraftLimit: z.string(),
    dailyLimit: z.string().nullable(),
    txnLimit: z.string().nullable(),
    categoryBlocks: z.array(z.string()),
    statusReason: z.string().nullable(),
});
export type WalletResponseDto = z.infer<typeof WalletResponseDtoSchema>;

export const WalletListItemResponseDtoSchema = z.object({
    id: z.string(),
    studentId: z.string(),
    admissionNo: z.string(),
    studentName: z.string(),
    status: z.string(),
    balance: z.string(),
    overdraftLimit: z.string(),
    dailyLimit: z.string().nullable(),
    txnLimit: z.string().nullable(),
});
export type WalletListItemResponseDto = z.infer<typeof WalletListItemResponseDtoSchema>;

export const WalletListResponseDtoSchema = z.object({
    items: z.array(WalletListItemResponseDtoSchema),
    total: z.number(),
});
export type WalletListResponseDto = z.infer<typeof WalletListResponseDtoSchema>;
