/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const TopUpDtoSchema = z.object({
    amount: z.string().regex(/^\d+(\.\d{1,4})?$/),
    method: z.enum(["CASH", "BANK", "CHEQUE", "CARD", "POS", "MPESA_STK", "MPESA_C2B", "MPESA_TILL", "BANK_TRANSFER"]),
    receiptId: z.string().uuid().optional(),
    idempotencyKey: z.string().optional(),
});
export type TopUpDto = z.infer<typeof TopUpDtoSchema>;

export const SpendDtoSchema = z.object({
    amount: z.string().regex(/^\d+(\.\d{1,4})?$/),
    servicePointId: z.string().uuid(),
    items: z.record(z.string(), z.unknown()).optional(),
    idempotencyKey: z.string().optional(),
});
export type SpendDto = z.infer<typeof SpendDtoSchema>;

export const TransferToFeesDtoSchema = z.object({
    amount: z.string().regex(/^\d+(\.\d{1,4})?$/),
    invoiceId: z.string().uuid(),
    approvalRef: z.string().uuid().optional(),
    idempotencyKey: z.string().optional(),
});
export type TransferToFeesDto = z.infer<typeof TransferToFeesDtoSchema>;

export const SweepToInvoicesDtoSchema = z.object({
    invoiceIds: z.array(z.string().uuid()).min(1),
    approvalRef: z.string().uuid().optional(),
});
export type SweepToInvoicesDto = z.infer<typeof SweepToInvoicesDtoSchema>;

export const SweepToInvoicesAllocationResponseDtoSchema = z.object({
    invoiceId: z.string(),
    amount: z.string(),
});
export type SweepToInvoicesAllocationResponseDto = z.infer<typeof SweepToInvoicesAllocationResponseDtoSchema>;

export const SweepToInvoicesShortfallResponseDtoSchema = z.object({
    invoiceId: z.string(),
    remainingBalance: z.string(),
});
export type SweepToInvoicesShortfallResponseDto = z.infer<typeof SweepToInvoicesShortfallResponseDtoSchema>;

export const SweepToInvoicesResponseDtoSchema = z.object({
    totalSwept: z.string(),
    allocations: z.array(SweepToInvoicesAllocationResponseDtoSchema),
    receiptId: z.string().nullable(),
    transactionId: z.string().nullable(),
    shortfall: z.array(SweepToInvoicesShortfallResponseDtoSchema),
});
export type SweepToInvoicesResponseDto = z.infer<typeof SweepToInvoicesResponseDtoSchema>;

export const TransferToWalletDtoSchema = z.object({
    toWalletId: z.string().uuid(),
    amount: z.string().regex(/^\d+(\.\d{1,4})?$/),
    approvalRef: z.string().uuid().optional(),
    idempotencyKey: z.string().optional(),
});
export type TransferToWalletDto = z.infer<typeof TransferToWalletDtoSchema>;

export const RefundPayoutTargetDtoSchema = z.object({
    guardianId: z.string().uuid(),
    accountRef: z.string().optional(),
});
export type RefundPayoutTargetDto = z.infer<typeof RefundPayoutTargetDtoSchema>;

export const RefundWalletDtoSchema = z.object({
    amount: z.string().regex(/^\d+(\.\d{1,4})?$/),
    payoutMethod: z.enum(["CASH", "BANK", "MPESA_B2C"]),
    payoutTarget: RefundPayoutTargetDtoSchema,
    approvalRef: z.string().uuid(),
    idempotencyKey: z.string().optional(),
});
export type RefundWalletDto = z.infer<typeof RefundWalletDtoSchema>;

export const AdjustWalletDtoSchema = z.object({
    amount: z.string().regex(/^\d+(\.\d{1,4})?$/),
    direction: z.enum(["D", "C"]),
    reasonCode: z.string(),
    approvalRef: z.string().uuid(),
    idempotencyKey: z.string().optional(),
});
export type AdjustWalletDto = z.infer<typeof AdjustWalletDtoSchema>;

export const CloseWalletRefundDtoSchema = z.object({
    payoutMethod: z.enum(["CASH", "BANK", "MPESA_B2C"]),
    payoutTarget: RefundPayoutTargetDtoSchema,
    approvalRef: z.string().uuid(),
});
export type CloseWalletRefundDto = z.infer<typeof CloseWalletRefundDtoSchema>;

export const CloseWalletDtoSchema = z.object({
    disposition: z.enum(["REFUND", "TRANSFER_TO_SIBLING", "APPLY_TO_FEES"]),
    reason: z.string().optional(),
    refund: CloseWalletRefundDtoSchema.optional(),
    transferToSiblingWalletId: z.string().uuid().optional(),
    applyToFeesInvoiceId: z.string().uuid().optional(),
    approvalRef: z.string().uuid().optional(),
});
export type CloseWalletDto = z.infer<typeof CloseWalletDtoSchema>;

export const WalletApprovalRequestResponseDtoSchema = z.object({
    instanceId: z.string(),
    status: z.string(),
});
export type WalletApprovalRequestResponseDto = z.infer<typeof WalletApprovalRequestResponseDtoSchema>;

export const WalletTransactionResponseDtoSchema = z.object({
    id: z.string(),
    walletId: z.string(),
    type: z.string(),
    amount: z.string(),
    direction: z.string(),
    balanceAfter: z.string(),
    servicePointId: z.string().nullable(),
    counterpartyWalletId: z.string().nullable(),
    receiptId: z.string().nullable(),
    journalId: z.string(),
    approvalRef: z.string().nullable(),
    reasonCode: z.string().nullable(),
    at: z.coerce.date(),
});
export type WalletTransactionResponseDto = z.infer<typeof WalletTransactionResponseDtoSchema>;

export const TransferToWalletResponseDtoSchema = z.object({
    outTransaction: WalletTransactionResponseDtoSchema,
    inTransaction: WalletTransactionResponseDtoSchema,
});
export type TransferToWalletResponseDto = z.infer<typeof TransferToWalletResponseDtoSchema>;
