/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateBankAccountDtoSchema = z.object({
    name: z.string(),
    kind: z.enum(["BANK", "CASH", "MPESA_SETTLEMENT", "PETTY"]),
    bankName: z.string().optional(),
    branch: z.string().optional(),
    accountNo: z.string().optional(),
    glAccountId: z.string().uuid(),
});
export type CreateBankAccountDto = z.infer<typeof CreateBankAccountDtoSchema>;

export const UpdateBankAccountDtoSchema = z.object({
    name: z.string().optional(),
    bankName: z.string().nullable().optional(),
    branch: z.string().nullable().optional(),
    accountNo: z.string().nullable().optional(),
    isActive: z.boolean().optional(),
});
export type UpdateBankAccountDto = z.infer<typeof UpdateBankAccountDtoSchema>;

export const BankAccountResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    kind: z.string(),
    bankName: z.string().nullable(),
    branch: z.string().nullable(),
    accountNo: z.string().nullable(),
    glAccountId: z.string(),
    isActive: z.boolean(),
});
export type BankAccountResponseDto = z.infer<typeof BankAccountResponseDtoSchema>;
