/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const IssueChequeLeafDtoSchema = z.object({
    bookId: z.string().uuid(),
    voucherId: z.string().uuid().optional(),
    payee: z.string(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type IssueChequeLeafDto = z.infer<typeof IssueChequeLeafDtoSchema>;

export const ReasonDtoSchema = z.object({
    reason: z.string(),
});
export type ReasonDto = z.infer<typeof ReasonDtoSchema>;

export const BankChequeLeafResponseDtoSchema = z.object({
    id: z.string(),
    bookId: z.string(),
    leafNo: z.number(),
    status: z.string(),
    voucherId: z.string().nullable(),
    payee: z.string().nullable(),
    amount: z.string().nullable(),
    issuedOn: z.string().nullable(),
    statusReason: z.string().nullable(),
});
export type BankChequeLeafResponseDto = z.infer<typeof BankChequeLeafResponseDtoSchema>;
