/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateDepositOrWithdrawalDtoSchema = z.object({
    accountId: z.string().uuid(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    slipRef: z.string().optional(),
    sourceSessionId: z.string().uuid().optional(),
});
export type CreateDepositOrWithdrawalDto = z.infer<typeof CreateDepositOrWithdrawalDtoSchema>;

export const DepositOrWithdrawalResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    accountId: z.string(),
    amount: z.string(),
    slipRef: z.string().nullable(),
    sourceSessionId: z.string().nullable(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
    ackBySender: z.string().nullable(),
    ackBySenderAt: z.coerce.date().nullable(),
    ackByReceiver: z.string().nullable(),
    ackByReceiverAt: z.coerce.date().nullable(),
});
export type DepositOrWithdrawalResponseDto = z.infer<typeof DepositOrWithdrawalResponseDtoSchema>;
