/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const StartReconciliationDtoSchema = z.object({
    accountId: z.string().uuid(),
    periodId: z.string().uuid(),
});
export type StartReconciliationDto = z.infer<typeof StartReconciliationDtoSchema>;

export const ManualMatchDtoSchema = z.object({
    statementLineId: z.string().uuid(),
    journalLineId: z.string().uuid(),
});
export type ManualMatchDto = z.infer<typeof ManualMatchDtoSchema>;

export const CreateAdjustmentDtoSchema = z.object({
    statementLineId: z.string().uuid(),
    kind: z.enum(["CHARGE", "INTEREST"]),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type CreateAdjustmentDto = z.infer<typeof CreateAdjustmentDtoSchema>;

export const ReopenReconciliationDtoSchema = z.object({
    reason: z.string(),
});
export type ReopenReconciliationDto = z.infer<typeof ReopenReconciliationDtoSchema>;

export const AutoMatchSuggestionDtoSchema = z.object({
    statementLineId: z.string(),
    journalLineId: z.string(),
    amount: z.string(),
});
export type AutoMatchSuggestionDto = z.infer<typeof AutoMatchSuggestionDtoSchema>;

export const AutoMatchResultDtoSchema = z.object({
    pass1Matches: z.number(),
    pass2Matches: z.number(),
    suggestions: z.array(AutoMatchSuggestionDtoSchema),
});
export type AutoMatchResultDto = z.infer<typeof AutoMatchResultDtoSchema>;

export const BankReconciliationResponseDtoSchema = z.object({
    id: z.string(),
    accountId: z.string(),
    periodId: z.string(),
    status: z.string(),
    bookBalance: z.string(),
    bankBalance: z.string(),
    outstanding: z.record(z.string(), z.unknown()),
    lockedBy: z.string().nullable(),
    lockedAt: z.coerce.date().nullable(),
});
export type BankReconciliationResponseDto = z.infer<typeof BankReconciliationResponseDtoSchema>;

export const BankReconMatchResponseDtoSchema = z.object({
    id: z.string(),
    reconciliationId: z.string(),
    statementLineId: z.string(),
    journalLineId: z.string().nullable(),
    adjustmentJournalId: z.string().nullable(),
});
export type BankReconMatchResponseDto = z.infer<typeof BankReconMatchResponseDtoSchema>;
