/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const BankStatementColumnMapDtoSchema = z.object({
    date: z.string(),
    description: z.string(),
    debit: z.string().optional(),
    credit: z.string().optional(),
    amount: z.string().optional(),
    ref: z.string().optional(),
});
export type BankStatementColumnMapDto = z.infer<typeof BankStatementColumnMapDtoSchema>;

export const BankStatementMappingTemplateDtoSchema = z.object({
    columnMap: z.record(z.string(), z.unknown()),
    dateFormat: z.string(),
    debitCreditConvention: z.enum(["SEPARATE_COLUMNS", "SIGNED_AMOUNT"]),
});
export type BankStatementMappingTemplateDto = z.infer<typeof BankStatementMappingTemplateDtoSchema>;

export const ImportBankStatementLinesDtoSchema = z.object({
    accountId: z.string().uuid(),
    fileId: z.string().uuid(),
    mappingTemplate: z.record(z.string(), z.unknown()),
    rawRows: z.array(z.record(z.string(), z.unknown())),
});
export type ImportBankStatementLinesDto = z.infer<typeof ImportBankStatementLinesDtoSchema>;

export const ImportBankStatementLinesResponseDtoSchema = z.object({
    importId: z.string(),
    insertedCount: z.number(),
    duplicateCount: z.number(),
});
export type ImportBankStatementLinesResponseDto = z.infer<typeof ImportBankStatementLinesResponseDtoSchema>;

export const BankStatementImportResponseDtoSchema = z.object({
    id: z.string(),
    accountId: z.string(),
    fileId: z.string(),
    mappingTemplate: z.record(z.string(), z.unknown()),
    importedAt: z.coerce.date(),
    lineCount: z.number(),
    duplicateCount: z.number(),
});
export type BankStatementImportResponseDto = z.infer<typeof BankStatementImportResponseDtoSchema>;
