/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateBankTransferDtoSchema = z.object({
    fromAccountId: z.string().uuid(),
    toAccountId: z.string().uuid(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type CreateBankTransferDto = z.infer<typeof CreateBankTransferDtoSchema>;

export const BankTransferResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    fromAccountId: z.string(),
    toAccountId: z.string(),
    amount: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
});
export type BankTransferResponseDto = z.infer<typeof BankTransferResponseDtoSchema>;
