/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const ReportColumnResponseDtoSchema = z.object({
    key: z.string(),
    label: z.string(),
    type: z.string(),
});
export type ReportColumnResponseDto = z.infer<typeof ReportColumnResponseDtoSchema>;

export const ReportDefinitionResponseDtoSchema = z.object({
    code: z.string(),
    name: z.string(),
    domain: z.string(),
    permissionCode: z.string(),
    paramsShape: z.record(z.string(), z.string()),
    columns: z.array(ReportColumnResponseDtoSchema),
});
export type ReportDefinitionResponseDto = z.infer<typeof ReportDefinitionResponseDtoSchema>;

export const ExecuteReportDtoSchema = z.object({
    params: z.record(z.string(), z.unknown()).optional(),
});
export type ExecuteReportDto = z.infer<typeof ExecuteReportDtoSchema>;

export const ReportResultResponseDtoSchema = z.object({
    rows: z.array(z.record(z.string(), z.unknown())),
    totals: z.record(z.string(), z.unknown()).optional(),
    generatedAt: z.string(),
});
export type ReportResultResponseDto = z.infer<typeof ReportResultResponseDtoSchema>;
