/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateScheduleDtoSchema = z.object({
    reportCode: z.string().max(40),
    params: z.record(z.string(), z.unknown()),
    cron: z.string().max(30),
    recipients: z.unknown(),
    format: z.enum(["PDF", "XLSX", "CSV"]),
});
export type CreateScheduleDto = z.infer<typeof CreateScheduleDtoSchema>;

export const UpdateScheduleDtoSchema = z.object({
    params: z.record(z.string(), z.unknown()).optional(),
    cron: z.string().max(30).optional(),
    recipients: z.unknown().optional(),
    format: z.enum(["PDF", "XLSX", "CSV"]).optional(),
    isActive: z.boolean().optional(),
});
export type UpdateScheduleDto = z.infer<typeof UpdateScheduleDtoSchema>;

export const ScheduleResponseDtoSchema = z.object({
    id: z.string(),
    reportCode: z.string(),
    params: z.record(z.string(), z.unknown()),
    cron: z.string(),
    recipients: z.unknown(),
    format: z.string(),
    ownerUserId: z.string(),
    isActive: z.boolean(),
    lastRunAt: z.string().nullable(),
    lastOk: z.boolean().nullable(),
});
export type ScheduleResponseDto = z.infer<typeof ScheduleResponseDtoSchema>;

export const RunDueDtoSchema = z.object({
    asOfDate: z.string().optional(),
});
export type RunDueDto = z.infer<typeof RunDueDtoSchema>;
