/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateCategoryDtoSchema = z.object({
    name: z.string().max(120),
    parentId: z.string().uuid().optional(),
    glExpenseAccountId: z.string().uuid(),
    budgetRequired: z.boolean().optional(),
    isActive: z.boolean().optional(),
});
export type CreateCategoryDto = z.infer<typeof CreateCategoryDtoSchema>;

export const UpdateCategoryDtoSchema = z.object({
    name: z.string().max(120).optional(),
    parentId: z.string().uuid().nullable().optional(),
    glExpenseAccountId: z.string().uuid().optional(),
    budgetRequired: z.boolean().optional(),
    isActive: z.boolean().optional(),
});
export type UpdateCategoryDto = z.infer<typeof UpdateCategoryDtoSchema>;

export const CategoryResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    parentId: z.string().nullable(),
    glExpenseAccountId: z.string(),
    budgetRequired: z.boolean(),
    isActive: z.boolean(),
});
export type CategoryResponseDto = z.infer<typeof CategoryResponseDtoSchema>;
