/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateClaimDtoSchema = z.object({
    staffUserId: z.string().uuid(),
    reimburseVia: z.enum(["PAYROLL", "DIRECT"]),
});
export type CreateClaimDto = z.infer<typeof CreateClaimDtoSchema>;

export const AddClaimLineDtoSchema = z.object({
    categoryId: z.string().uuid(),
    description: z.string().max(200),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    expenseDate: z.string(),
    receiptFileId: z.string().uuid().optional(),
});
export type AddClaimLineDto = z.infer<typeof AddClaimLineDtoSchema>;

export const UpdateClaimLineDtoSchema = z.object({
    categoryId: z.string().uuid().optional(),
    description: z.string().max(200).optional(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    expenseDate: z.string().optional(),
    receiptFileId: z.string().uuid().nullable().optional(),
});
export type UpdateClaimLineDto = z.infer<typeof UpdateClaimLineDtoSchema>;

export const ReimburseClaimDtoSchema = z.object({
    method: z.enum(["CASH", "BANK", "PETTY_CASH", "MPESA", "CHEQUE"]).optional(),
});
export type ReimburseClaimDto = z.infer<typeof ReimburseClaimDtoSchema>;

export const ClaimResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    staffUserId: z.string(),
    total: z.string(),
    status: z.string(),
    reimburseVia: z.string(),
    approvalRef: z.string().nullable(),
});
export type ClaimResponseDto = z.infer<typeof ClaimResponseDtoSchema>;

export const ClaimLineResponseDtoSchema = z.object({
    id: z.string(),
    claimId: z.string(),
    lineNo: z.number(),
    categoryId: z.string(),
    description: z.string(),
    amount: z.string(),
    expenseDate: z.string(),
    receiptFileId: z.string().nullable(),
});
export type ClaimLineResponseDto = z.infer<typeof ClaimLineResponseDtoSchema>;
