/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateFloatDtoSchema = z.object({
    custodianUserId: z.string().uuid(),
    ceiling: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type CreateFloatDto = z.infer<typeof CreateFloatDtoSchema>;

export const UpdateFloatCeilingDtoSchema = z.object({
    ceiling: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type UpdateFloatCeilingDto = z.infer<typeof UpdateFloatCeilingDtoSchema>;

export const FloatResponseDtoSchema = z.object({
    id: z.string(),
    custodianUserId: z.string(),
    ceiling: z.string(),
    balance: z.string(),
});
export type FloatResponseDto = z.infer<typeof FloatResponseDtoSchema>;

export const SpendDtoSchema = z.object({
    categoryId: z.string().uuid(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    receiptFileId: z.string().uuid().optional(),
});
export type SpendDto = z.infer<typeof SpendDtoSchema>;

export const PettyCashVoucherResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    floatId: z.string(),
    categoryId: z.string(),
    amount: z.string(),
    receiptFileId: z.string().nullable(),
    status: z.string(),
    journalId: z.string().nullable(),
});
export type PettyCashVoucherResponseDto = z.infer<typeof PettyCashVoucherResponseDtoSchema>;

export const ReplenishmentResponseDtoSchema = z.object({
    id: z.string(),
    floatId: z.string(),
    amount: z.string(),
    voucherIds: z.array(z.string()),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
});
export type ReplenishmentResponseDto = z.infer<typeof ReplenishmentResponseDtoSchema>;
