/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const RecurringTemplateDtoSchema = z.object({
    payeeType: z.enum(["SUPPLIER", "STAFF", "OTHER"]),
    payeeRef: z.record(z.string(), z.unknown()),
    categoryId: z.string().uuid(),
    costCenterId: z.string().uuid().nullable().optional(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    method: z.enum(["CASH", "BANK", "PETTY_CASH", "MPESA", "CHEQUE"]),
    narrative: z.string(),
});
export type RecurringTemplateDto = z.infer<typeof RecurringTemplateDtoSchema>;

export const CreateRecurringDtoSchema = z.object({
    template: RecurringTemplateDtoSchema,
    scheduleCron: z.string(),
    nextRunOn: z.string(),
});
export type CreateRecurringDto = z.infer<typeof CreateRecurringDtoSchema>;

export const UpdateRecurringDtoSchema = z.object({
    template: RecurringTemplateDtoSchema.optional(),
    scheduleCron: z.string().optional(),
    nextRunOn: z.string().optional(),
    isActive: z.boolean().optional(),
});
export type UpdateRecurringDto = z.infer<typeof UpdateRecurringDtoSchema>;

export const RecurringResponseDtoSchema = z.object({
    id: z.string(),
    template: z.record(z.string(), z.unknown()),
    scheduleCron: z.string(),
    nextRunOn: z.string(),
    lastVoucherId: z.string().nullable(),
    isActive: z.boolean(),
});
export type RecurringResponseDto = z.infer<typeof RecurringResponseDtoSchema>;

export const RunDueDtoSchema = z.object({
    asOfDate: z.string().optional(),
});
export type RunDueDto = z.infer<typeof RunDueDtoSchema>;

export const RunDueResultDtoSchema = z.object({
    recurringId: z.string(),
    voucherId: z.string(),
    nextRunOn: z.string(),
});
export type RunDueResultDto = z.infer<typeof RunDueResultDtoSchema>;
