/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateVoucherDtoSchema = z.object({
    payeeType: z.enum(["SUPPLIER", "STAFF", "OTHER"]),
    payeeRef: z.record(z.string(), z.unknown()),
    categoryId: z.string().uuid(),
    costCenterId: z.string().uuid().optional(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    method: z.enum(["CASH", "BANK", "PETTY_CASH", "MPESA", "CHEQUE"]),
    narrative: z.string(),
});
export type CreateVoucherDto = z.infer<typeof CreateVoucherDtoSchema>;

export const UpdateVoucherDtoSchema = z.object({
    payeeType: z.enum(["SUPPLIER", "STAFF", "OTHER"]).optional(),
    payeeRef: z.record(z.string(), z.unknown()).optional(),
    categoryId: z.string().uuid().optional(),
    costCenterId: z.string().uuid().nullable().optional(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    method: z.enum(["CASH", "BANK", "PETTY_CASH", "MPESA", "CHEQUE"]).optional(),
    narrative: z.string().optional(),
});
export type UpdateVoucherDto = z.infer<typeof UpdateVoucherDtoSchema>;

export const VoucherResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    payeeType: z.string(),
    payeeRef: z.record(z.string(), z.unknown()),
    categoryId: z.string(),
    costCenterId: z.string().nullable(),
    amount: z.string(),
    method: z.string(),
    narrative: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
});
export type VoucherResponseDto = z.infer<typeof VoucherResponseDtoSchema>;
