/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateBulkAllocationLineDtoSchema = z.object({
    admissionNo: z.string().max(30),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type CreateBulkAllocationLineDto = z.infer<typeof CreateBulkAllocationLineDtoSchema>;

export const CreateBulkAllocationBatchDtoSchema = z.object({
    instrument: z.record(z.string(), z.unknown()),
    lines: z.array(CreateBulkAllocationLineDtoSchema).min(1),
    bankAccountId: z.string().uuid(),
});
export type CreateBulkAllocationBatchDto = z.infer<typeof CreateBulkAllocationBatchDtoSchema>;

export const BulkAllocationBatchResponseDtoSchema = z.object({
    id: z.string(),
    instrument: z.record(z.string(), z.unknown()),
    total: z.string(),
    status: z.string(),
    createdReceipts: z.number(),
    bankAccountId: z.string(),
});
export type BulkAllocationBatchResponseDto = z.infer<typeof BulkAllocationBatchResponseDtoSchema>;

export const BulkAllocationBatchLineResponseDtoSchema = z.object({
    id: z.string(),
    batchId: z.string(),
    studentId: z.string(),
    amount: z.string(),
    receiptId: z.string().nullable(),
});
export type BulkAllocationBatchLineResponseDto = z.infer<typeof BulkAllocationBatchLineResponseDtoSchema>;
