/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const OpenSessionDtoSchema = z.object({
    till: z.string().max(30),
    floatAmount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type OpenSessionDto = z.infer<typeof OpenSessionDtoSchema>;

export const CloseSessionApprovalDtoSchema = z.object({
    supervisorId: z.string(),
    varianceReason: z.string(),
});
export type CloseSessionApprovalDto = z.infer<typeof CloseSessionApprovalDtoSchema>;

export const CloseSessionDtoSchema = z.object({
    counted: z.record(z.string(), z.unknown()),
    approval: z.record(z.string(), z.unknown()).optional(),
});
export type CloseSessionDto = z.infer<typeof CloseSessionDtoSchema>;

export const CashierSessionResponseDtoSchema = z.object({
    id: z.string(),
    cashierId: z.string(),
    till: z.string(),
    status: z.string(),
    openedAt: z.coerce.date(),
    floatAmount: z.string(),
    closedAt: z.coerce.date().nullable(),
    counted: z.record(z.string(), z.unknown()).nullable(),
    expectedTotals: z.record(z.string(), z.unknown()).nullable(),
    varianceAmount: z.string().nullable(),
    varianceReason: z.string().nullable(),
    supervisorId: z.string().nullable(),
});
export type CashierSessionResponseDto = z.infer<typeof CashierSessionResponseDtoSchema>;
