/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const BounceChequeDtoSchema = z.object({
    applyBounceFee: z.boolean().optional(),
});
export type BounceChequeDto = z.infer<typeof BounceChequeDtoSchema>;

export const ChequeResponseDtoSchema = z.object({
    id: z.string(),
    bankName: z.string(),
    chequeNo: z.string(),
    chequeDate: z.string(),
    drawer: z.string(),
    amount: z.string(),
    status: z.string(),
    statusChangedAt: z.coerce.date().nullable(),
    bounceFeeApplied: z.boolean(),
});
export type ChequeResponseDto = z.infer<typeof ChequeResponseDtoSchema>;
