/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const InitiateStkDtoSchema = z.object({
    studentId: z.string().uuid(),
    amountKes: z.string().regex(/^-?\d+(\.\d+)?$/),
    msisdn: z.string().max(15),
    accountRef: z.string().max(30),
    invoiceIds: z.array(z.string().uuid()).optional(),
});
export type InitiateStkDto = z.infer<typeof InitiateStkDtoSchema>;

export const InitiateB2cDtoSchema = z.object({
    amountKes: z.string().regex(/^-?\d+(\.\d+)?$/),
    msisdn: z.string().max(15),
    remarks: z.string().max(100),
    originatingReason: z.string().max(100).optional(),
});
export type InitiateB2cDto = z.infer<typeof InitiateB2cDtoSchema>;

export const MpesaTransactionResponseDtoSchema = z.object({
    id: z.string(),
    kind: z.string(),
    shortcode: z.string(),
    msisdnMasked: z.string(),
    amount: z.string(),
    mpesaRef: z.string().nullable(),
    checkoutRequestId: z.string().nullable(),
    conversationId: z.string().nullable(),
    state: z.string(),
    matchedReceiptId: z.string().nullable(),
});
export type MpesaTransactionResponseDto = z.infer<typeof MpesaTransactionResponseDtoSchema>;
