/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CaptureReceiptChequeDetailsDtoSchema = z.object({
    bankName: z.string().max(80),
    chequeNo: z.string().max(30),
    chequeDate: z.string(),
    drawer: z.string().max(120),
});
export type CaptureReceiptChequeDetailsDto = z.infer<typeof CaptureReceiptChequeDetailsDtoSchema>;

export const CaptureReceiptSplitDtoSchema = z.object({
    method: z.enum(["CASH", "BANK", "CHEQUE", "CARD", "POS", "MPESA_STK", "MPESA_C2B", "MPESA_TILL", "WALLET", "BANK_TRANSFER", "CREDIT_BALANCE"]),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    bankAccountId: z.string().optional(),
    externalRef: z.string().max(60).optional(),
    chequeDetails: CaptureReceiptChequeDetailsDtoSchema.optional(),
    mpesaTransactionId: z.string().optional(),
});
export type CaptureReceiptSplitDto = z.infer<typeof CaptureReceiptSplitDtoSchema>;

export const CaptureReceiptDtoSchema = z.object({
    studentId: z.string().uuid(),
    payerName: z.string().max(120),
    payerPhone: z.string().max(20).optional(),
    receiptDate: z.string(),
    total: z.string().regex(/^-?\d+(\.\d+)?$/),
    splits: z.array(CaptureReceiptSplitDtoSchema).min(1),
    sessionId: z.string().uuid().optional(),
    idempotencyKey: z.string().max(64).optional(),
    invoiceIds: z.array(z.string().uuid()).optional(),
});
export type CaptureReceiptDto = z.infer<typeof CaptureReceiptDtoSchema>;

export const ReverseReceiptDtoSchema = z.object({
    reasonCode: z.enum(["ERROR", "BOUNCE", "DUPLICATE", "FRAUD"]),
    approvalRef: z.string().uuid(),
});
export type ReverseReceiptDto = z.infer<typeof ReverseReceiptDtoSchema>;

export const ReceiptSplitResponseDtoSchema = z.object({
    id: z.string(),
    receiptId: z.string(),
    method: z.string(),
    amount: z.string(),
    bankAccountId: z.string().nullable(),
    chequeId: z.string().nullable(),
    mpesaTransactionId: z.string().nullable(),
    externalRef: z.string().nullable(),
});
export type ReceiptSplitResponseDto = z.infer<typeof ReceiptSplitResponseDtoSchema>;

export const ReceiptAllocationResponseDtoSchema = z.object({
    id: z.string(),
    receiptId: z.string(),
    invoiceId: z.string().nullable(),
    installmentId: z.string().nullable(),
    toPrepayment: z.boolean(),
    amount: z.string(),
    invoiceNumber: z.string().nullable(),
});
export type ReceiptAllocationResponseDto = z.infer<typeof ReceiptAllocationResponseDtoSchema>;

export const ReceiptResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    studentId: z.string(),
    payerName: z.string(),
    payerPhone: z.string().nullable(),
    receiptDate: z.string(),
    total: z.string(),
    status: z.string(),
    reversalOfId: z.string().nullable(),
    reversalReason: z.string().nullable(),
    approvalRef: z.string().nullable(),
    cashierId: z.string(),
    sessionId: z.string().nullable(),
    journalId: z.string().nullable(),
    idempotencyKey: z.string().nullable(),
    balanceAfter: z.string(),
    reprintCount: z.number(),
});
export type ReceiptResponseDto = z.infer<typeof ReceiptResponseDtoSchema>;

export const ReceiptDetailResponseDtoSchema = ReceiptResponseDtoSchema.merge(z.object({
    splits: z.array(ReceiptSplitResponseDtoSchema),
    allocations: z.array(ReceiptAllocationResponseDtoSchema),
    verificationToken: z.string().nullable(),
}));
export type ReceiptDetailResponseDto = z.infer<typeof ReceiptDetailResponseDtoSchema>;

export const ReceiptListItemResponseDtoSchema = ReceiptResponseDtoSchema.merge(z.object({
    studentName: z.string(),
    cashierName: z.string(),
}));
export type ReceiptListItemResponseDto = z.infer<typeof ReceiptListItemResponseDtoSchema>;

export const ReceiptListResponseDtoSchema = z.object({
    items: z.array(ReceiptListItemResponseDtoSchema),
    total: z.number(),
});
export type ReceiptListResponseDto = z.infer<typeof ReceiptListResponseDtoSchema>;

export const ReversalApprovalResponseDtoSchema = z.object({
    instanceId: z.string(),
    status: z.string(),
});
export type ReversalApprovalResponseDto = z.infer<typeof ReversalApprovalResponseDtoSchema>;

export const ApplyStudentCreditDtoSchema = z.object({
    studentId: z.string().uuid(),
    invoiceIds: z.array(z.string().uuid()).min(1),
});
export type ApplyStudentCreditDto = z.infer<typeof ApplyStudentCreditDtoSchema>;

export const ApplyStudentCreditAllocationResponseDtoSchema = z.object({
    invoiceId: z.string(),
    amount: z.string(),
});
export type ApplyStudentCreditAllocationResponseDto = z.infer<typeof ApplyStudentCreditAllocationResponseDtoSchema>;

export const ApplyStudentCreditShortfallResponseDtoSchema = z.object({
    invoiceId: z.string(),
    remainingBalance: z.string(),
});
export type ApplyStudentCreditShortfallResponseDto = z.infer<typeof ApplyStudentCreditShortfallResponseDtoSchema>;

export const ApplyStudentCreditResponseDtoSchema = z.object({
    totalApplied: z.string(),
    allocations: z.array(ApplyStudentCreditAllocationResponseDtoSchema),
    receiptId: z.string().nullable(),
    shortfall: z.array(ApplyStudentCreditShortfallResponseDtoSchema),
});
export type ApplyStudentCreditResponseDto = z.infer<typeof ApplyStudentCreditResponseDtoSchema>;
