/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const MatchSuspenseItemDtoSchema = z.object({
    studentId: z.string().uuid(),
});
export type MatchSuspenseItemDto = z.infer<typeof MatchSuspenseItemDtoSchema>;

export const ReverseSuspenseRefundDtoSchema = z.object({
    approvalRef: z.string().uuid(),
});
export type ReverseSuspenseRefundDto = z.infer<typeof ReverseSuspenseRefundDtoSchema>;

export const SuspenseItemResponseDtoSchema = z.object({
    id: z.string(),
    source: z.string(),
    amount: z.string(),
    externalRef: z.string(),
    receivedAt: z.coerce.date(),
    state: z.string(),
    resolvedReceiptId: z.string().nullable(),
    resolvedBy: z.string().nullable(),
    resolvedAt: z.coerce.date().nullable(),
    resolutionNote: z.string().nullable(),
});
export type SuspenseItemResponseDto = z.infer<typeof SuspenseItemResponseDtoSchema>;

export const SuspenseRefundApprovalResponseDtoSchema = z.object({
    instanceId: z.string(),
    status: z.string(),
});
export type SuspenseRefundApprovalResponseDto = z.infer<typeof SuspenseRefundApprovalResponseDtoSchema>;
