/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateContractDtoSchema = z.object({
    supplierId: z.string().uuid(),
    title: z.string().max(160),
    startsOn: z.string(),
    endsOn: z.string(),
    value: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    renewalAlertDays: z.number().min(0).int().optional(),
    documentFileId: z.string().uuid().optional(),
});
export type CreateContractDto = z.infer<typeof CreateContractDtoSchema>;

export const UpdateContractDtoSchema = z.object({
    title: z.string().max(160).optional(),
    startsOn: z.string().optional(),
    endsOn: z.string().optional(),
    value: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    renewalAlertDays: z.number().min(0).int().optional(),
    documentFileId: z.string().uuid().optional(),
});
export type UpdateContractDto = z.infer<typeof UpdateContractDtoSchema>;

export const ContractResponseDtoSchema = z.object({
    id: z.string(),
    supplierId: z.string(),
    title: z.string(),
    startsOn: z.string(),
    endsOn: z.string(),
    value: z.string().nullable(),
    renewalAlertDays: z.number(),
    documentFileId: z.string().nullable(),
    status: z.string(),
});
export type ContractResponseDto = z.infer<typeof ContractResponseDtoSchema>;
