/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const ReceiveGrnLineDtoSchema = z.object({
    poLineId: z.string().uuid(),
    receivedQty: z.string().regex(/^-?\d+(\.\d+)?$/),
    rejectedQty: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    rejectionReason: z.string().optional(),
    unitCost: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type ReceiveGrnLineDto = z.infer<typeof ReceiveGrnLineDtoSchema>;

export const ReceiveGrnDtoSchema = z.object({
    poId: z.string().uuid(),
    lines: z.array(ReceiveGrnLineDtoSchema).min(1),
    notes: z.string().optional(),
});
export type ReceiveGrnDto = z.infer<typeof ReceiveGrnDtoSchema>;

export const GrnResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    poId: z.string(),
    receivedBy: z.string(),
    receivedAt: z.coerce.date(),
    status: z.string(),
    journalId: z.string().nullable(),
    notes: z.string().nullable(),
});
export type GrnResponseDto = z.infer<typeof GrnResponseDtoSchema>;

export const GrnLineResponseDtoSchema = z.object({
    id: z.string(),
    grnId: z.string(),
    poLineId: z.string(),
    receivedQty: z.string(),
    rejectedQty: z.string(),
    rejectionReason: z.string().nullable(),
    unitCost: z.string(),
});
export type GrnLineResponseDto = z.infer<typeof GrnLineResponseDtoSchema>;
