/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreatePaymentVoucherAllocationDtoSchema = z.object({
    supplierInvoiceId: z.string().uuid(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type CreatePaymentVoucherAllocationDto = z.infer<typeof CreatePaymentVoucherAllocationDtoSchema>;

export const CreatePaymentVoucherDtoSchema = z.object({
    supplierId: z.string().uuid(),
    method: z.enum(["BANK", "CHEQUE", "MPESA", "CASH"]),
    bankAccountId: z.string().uuid().optional(),
    chequeLeafId: z.string().uuid().optional(),
    allocations: z.array(CreatePaymentVoucherAllocationDtoSchema).min(1),
});
export type CreatePaymentVoucherDto = z.infer<typeof CreatePaymentVoucherDtoSchema>;

export const PaymentVoucherResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    supplierId: z.string(),
    method: z.string(),
    bankAccountId: z.string().nullable(),
    chequeLeafId: z.string().nullable(),
    total: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
    remittanceSent: z.boolean(),
});
export type PaymentVoucherResponseDto = z.infer<typeof PaymentVoucherResponseDtoSchema>;

export const PaymentVoucherAllocationResponseDtoSchema = z.object({
    id: z.string(),
    voucherId: z.string(),
    supplierInvoiceId: z.string(),
    amount: z.string(),
});
export type PaymentVoucherAllocationResponseDto = z.infer<typeof PaymentVoucherAllocationResponseDtoSchema>;
