/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const PurchaseOrderLineDtoSchema = z.object({
    itemId: z.string().uuid().optional(),
    description: z.string().max(200),
    qty: z.string().regex(/^-?\d+(\.\d+)?$/),
    unitPrice: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type PurchaseOrderLineDto = z.infer<typeof PurchaseOrderLineDtoSchema>;

export const CreatePurchaseOrderDtoSchema = z.object({
    requisitionId: z.string().uuid().optional(),
    quotationId: z.string().uuid().optional(),
    supplierId: z.string().uuid(),
    orderDate: z.string().optional(),
    deliveryTerms: z.string().optional(),
    lines: z.array(PurchaseOrderLineDtoSchema).min(1),
});
export type CreatePurchaseOrderDto = z.infer<typeof CreatePurchaseOrderDtoSchema>;

export const RevisePurchaseOrderDtoSchema = z.object({
    supplierId: z.string().uuid().optional(),
    deliveryTerms: z.string().optional(),
    lines: z.array(PurchaseOrderLineDtoSchema).optional(),
});
export type RevisePurchaseOrderDto = z.infer<typeof RevisePurchaseOrderDtoSchema>;

export const PurchaseOrderResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    revision: z.number(),
    supersedesId: z.string().nullable(),
    supplierId: z.string(),
    requisitionId: z.string().nullable(),
    quotationId: z.string().nullable(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    orderDate: z.string(),
    deliveryTerms: z.string().nullable(),
    paymentTermsDays: z.number(),
    subtotal: z.string(),
    taxAmount: z.string(),
    total: z.string(),
    issuedAt: z.coerce.date().nullable(),
});
export type PurchaseOrderResponseDto = z.infer<typeof PurchaseOrderResponseDtoSchema>;

export const PurchaseOrderLineResponseDtoSchema = z.object({
    id: z.string(),
    poId: z.string(),
    lineNo: z.number(),
    itemId: z.string().nullable(),
    description: z.string(),
    qty: z.string(),
    unitPrice: z.string(),
    receivedQty: z.string(),
});
export type PurchaseOrderLineResponseDto = z.infer<typeof PurchaseOrderLineResponseDtoSchema>;
