/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateQuotationLineDtoSchema = z.object({
    itemId: z.string().uuid().optional(),
    description: z.string().max(200),
    qty: z.string().regex(/^-?\d+(\.\d+)?$/),
    unitPrice: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type CreateQuotationLineDto = z.infer<typeof CreateQuotationLineDtoSchema>;

export const CreateQuotationDtoSchema = z.object({
    requisitionId: z.string().uuid(),
    supplierId: z.string().uuid(),
    quoteDate: z.string(),
    validUntil: z.string().optional(),
    documentFileId: z.string().uuid().optional(),
    terms: z.string().optional(),
    lines: z.array(CreateQuotationLineDtoSchema).min(1),
});
export type CreateQuotationDto = z.infer<typeof CreateQuotationDtoSchema>;

export const AwardQuotationDtoSchema = z.object({
    awardReason: z.string().min(1),
});
export type AwardQuotationDto = z.infer<typeof AwardQuotationDtoSchema>;

export const QuotationResponseDtoSchema = z.object({
    id: z.string(),
    requisitionId: z.string(),
    supplierId: z.string(),
    quoteDate: z.string(),
    validUntil: z.string().nullable(),
    documentFileId: z.string().nullable(),
    total: z.string(),
    terms: z.string().nullable(),
    isAwarded: z.boolean(),
    awardReason: z.string().nullable(),
});
export type QuotationResponseDto = z.infer<typeof QuotationResponseDtoSchema>;

export const QuotationLineResponseDtoSchema = z.object({
    id: z.string(),
    quotationId: z.string(),
    itemId: z.string().nullable(),
    description: z.string(),
    qty: z.string(),
    unitPrice: z.string(),
});
export type QuotationLineResponseDto = z.infer<typeof QuotationLineResponseDtoSchema>;
