/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateRequisitionDtoSchema = z.object({
    departmentId: z.string().uuid(),
    justification: z.string(),
});
export type CreateRequisitionDto = z.infer<typeof CreateRequisitionDtoSchema>;

export const CreateRequisitionLineDtoSchema = z.object({
    itemId: z.string().uuid().optional(),
    freeText: z.string().max(200).optional(),
    qty: z.string().regex(/^-?\d+(\.\d+)?$/),
    estPrice: z.string().regex(/^-?\d+(\.\d+)?$/),
    budgetLineId: z.string().uuid().optional(),
});
export type CreateRequisitionLineDto = z.infer<typeof CreateRequisitionLineDtoSchema>;

export const UpdateRequisitionLineDtoSchema = z.object({
    itemId: z.string().uuid().optional(),
    freeText: z.string().max(200).optional(),
    qty: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    estPrice: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    budgetLineId: z.string().uuid().optional(),
});
export type UpdateRequisitionLineDto = z.infer<typeof UpdateRequisitionLineDtoSchema>;

export const RequisitionResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    requestedBy: z.string(),
    departmentId: z.string(),
    justification: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    budgetSnapshot: z.record(z.string(), z.unknown()).nullable(),
    totalEstimate: z.string(),
});
export type RequisitionResponseDto = z.infer<typeof RequisitionResponseDtoSchema>;

export const RequisitionLineResponseDtoSchema = z.object({
    id: z.string(),
    requisitionId: z.string(),
    itemId: z.string().nullable(),
    freeText: z.string().nullable(),
    qty: z.string(),
    estPrice: z.string(),
    budgetLineId: z.string().nullable(),
});
export type RequisitionLineResponseDto = z.infer<typeof RequisitionLineResponseDtoSchema>;
