/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CaptureSupplierInvoiceLineDtoSchema = z.object({
    poLineId: z.string().uuid(),
    qty: z.string().regex(/^-?\d+(\.\d+)?$/),
    unitPrice: z.string().regex(/^-?\d+(\.\d+)?$/),
});
export type CaptureSupplierInvoiceLineDto = z.infer<typeof CaptureSupplierInvoiceLineDtoSchema>;

export const CaptureSupplierInvoiceDtoSchema = z.object({
    supplierId: z.string().uuid(),
    poId: z.string().uuid().optional(),
    supplierRef: z.string(),
    invoiceDate: z.string(),
    dueDate: z.string(),
    total: z.string().regex(/^-?\d+(\.\d+)?$/),
    lines: z.array(CaptureSupplierInvoiceLineDtoSchema).optional(),
});
export type CaptureSupplierInvoiceDto = z.infer<typeof CaptureSupplierInvoiceDtoSchema>;

export const ResolveMatchExceptionDtoSchema = z.object({
    resolution: z.enum(["ACCEPT_VARIANCE", "REJECT"]),
    note: z.string().min(1),
});
export type ResolveMatchExceptionDto = z.infer<typeof ResolveMatchExceptionDtoSchema>;

export const SupplierInvoiceResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    supplierRef: z.string(),
    supplierId: z.string(),
    poId: z.string().nullable(),
    invoiceDate: z.string(),
    dueDate: z.string(),
    total: z.string(),
    status: z.string(),
    matchVariance: z.record(z.string(), z.unknown()).nullable(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
    paidAmount: z.string(),
});
export type SupplierInvoiceResponseDto = z.infer<typeof SupplierInvoiceResponseDtoSchema>;
