/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateSupplierDtoSchema = z.object({
    name: z.string().max(120),
    tradingName: z.string().max(120).optional(),
    kraPin: z.string().max(15).optional(),
    contacts: z.record(z.string(), z.unknown()).optional(),
    paymentDetails: z.record(z.string(), z.unknown()).optional(),
    categories: z.array(z.string()).max(40).optional(),
    paymentTermsDays: z.number().min(0).int().optional(),
});
export type CreateSupplierDto = z.infer<typeof CreateSupplierDtoSchema>;

export const UpdateSupplierDtoSchema = z.object({
    name: z.string().max(120).optional(),
    tradingName: z.string().max(120).optional(),
    kraPin: z.string().max(15).optional(),
    contacts: z.record(z.string(), z.unknown()).optional(),
    paymentDetails: z.record(z.string(), z.unknown()).optional(),
    categories: z.array(z.string()).max(40).optional(),
    paymentTermsDays: z.number().min(0).int().optional(),
});
export type UpdateSupplierDto = z.infer<typeof UpdateSupplierDtoSchema>;

export const BlacklistSupplierDtoSchema = z.object({
    reason: z.string().min(1),
});
export type BlacklistSupplierDto = z.infer<typeof BlacklistSupplierDtoSchema>;

export const SetManualRatingDtoSchema = z.object({
    score: z.number().max(5).min(1),
});
export type SetManualRatingDto = z.infer<typeof SetManualRatingDtoSchema>;

export const SupplierResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    tradingName: z.string().nullable(),
    kraPin: z.string().nullable(),
    contacts: z.record(z.string(), z.unknown()),
    paymentDetails: z.record(z.string(), z.unknown()),
    categories: z.array(z.string()),
    paymentTermsDays: z.number(),
    status: z.string(),
    blacklistReason: z.string().nullable(),
    ratingDelivery: z.string().nullable(),
    ratingQuality: z.string().nullable(),
    ratingManual: z.string().nullable(),
});
export type SupplierResponseDto = z.infer<typeof SupplierResponseDtoSchema>;
