/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const RunBackupDtoSchema = z.object({
    kind: z.enum(["SCHEDULED", "MANUAL", "PRE_UPDATE"]),
});
export type RunBackupDto = z.infer<typeof RunBackupDtoSchema>;

export const BackupRunResponseDtoSchema = z.object({
    id: z.string(),
    startedAt: z.string(),
    finishedAt: z.string().nullable(),
    kind: z.string(),
    status: z.string(),
    sizeBytes: z.string().nullable(),
    sha256: z.string().nullable(),
    destinations: z.array(z.unknown()),
    manifest: z.unknown(),
    error: z.string().nullable(),
    createdAt: z.string(),
});
export type BackupRunResponseDto = z.infer<typeof BackupRunResponseDtoSchema>;

export const ListBackupRunsQueryDtoSchema = z.object({
    kind: z.enum(["SCHEDULED", "MANUAL", "PRE_UPDATE"]).optional(),
    status: z.enum(["RUNNING", "OK", "FAILED"]).optional(),
    page: z.number().min(1).int().optional(),
    pageSize: z.number().min(1).int().optional(),
});
export type ListBackupRunsQueryDto = z.infer<typeof ListBackupRunsQueryDtoSchema>;

export const ListBackupRunsResponseDtoSchema = z.object({
    items: z.array(BackupRunResponseDtoSchema),
    meta: z.object({
    total: z.number(),
    page: z.number(),
    pageSize: z.number(),
    pageCount: z.number(),
  }),
});
export type ListBackupRunsResponseDto = z.infer<typeof ListBackupRunsResponseDtoSchema>;

export const VerifyRestoreTargetDtoSchema = z.object({
    host: z.string(),
    port: z.number().int(),
    database: z.string(),
    user: z.string(),
    password: z.string(),
});
export type VerifyRestoreTargetDto = z.infer<typeof VerifyRestoreTargetDtoSchema>;

export const VerifyRestoreDtoSchema = z.object({
    target: VerifyRestoreTargetDtoSchema,
});
export type VerifyRestoreDto = z.infer<typeof VerifyRestoreDtoSchema>;

export const PruneBackupsResponseDtoSchema = z.object({
    prunedCount: z.number(),
    prunedRunIds: z.array(z.string()),
});
export type PruneBackupsResponseDto = z.infer<typeof PruneBackupsResponseDtoSchema>;
