/**
 * Codegen entrypoint for Part 2 (full zod DTO coverage). Run via
 * `pnpm --filter contracts run generate:zod` (invokes ts-node against
 * tsconfig.codegen.json). See docs/phase-5/PROGRESS.md's "packages/contracts"
 * section for the full design rationale.
 *
 * Pipeline:
 *   1. Source-scan every `*.dto.ts` file under packages/server/src (dto-scan.ts)
 *      — gives the ground-truth class/property list + `@Type(() => X)` nested
 *      references + import statements (for disambiguating duplicate class names).
 *   2. Build a global class registry (className -> every class sharing that
 *      name, since several DTO class names repeat verbatim across unrelated
 *      modules — see decorator-to-zod.ts's own doc comment) with each entry's
 *      output file path + zod schema export name, BEFORE emitting anything, so
 *      cross-file nested-type imports can be wired up in one pass.
 *   3. For each source DTO file, `require()` it for real (this process already
 *      runs under ts-node with the same experimentalDecorators/emitDecoratorMetadata
 *      settings packages/server itself compiles under) and read each class's
 *      REAL class-validator metadata via `getMetadataStorage().getTargetValidationMetadatas()`
 *      — the runtime reflection this task's brief specifically asked for.
 *   4. Translate each property (decorator-to-zod.ts) and emit one mirrored
 *      `*.schema.ts` file per source `*.dto.ts` file, topologically ordered
 *      within the file so same-file nested references are declared before use.
 *   5. Emit `src/index.ts`, a barrel re-exporting every generated schema plus
 *      the OpenAPI-derived types and the typed client (Part 1).
 */
import "reflect-metadata";
import * as fs from "node:fs";
import * as path from "node:path";
import { getMetadataStorage } from "class-validator";
import { findAllDtoFiles, scanDtoFile, type ScannedDtoClass } from "./dto-scan";
import { computeOutRelativePath, schemaVarNameFor } from "./naming";
import {
  translateProperty,
  resolveClassRef,
  type ClassRegistry,
  type ClassRegistryEntry,
  type ValidationMetadata,
} from "./decorator-to-zod";

const CONTRACTS_SRC = path.resolve(__dirname, "../src");
const GENERATED_BANNER = `/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with \`pnpm --filter contracts run generate:zod\`
 * (or \`generate\`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
`;

function computeImportSpecifier(fromOutRelPath: string, toOutRelPath: string): string {
  const fromDir = path.posix.dirname(fromOutRelPath);
  const toNoExt = toOutRelPath.replace(/\.ts$/, "");
  let rel = path.posix.relative(fromDir, toNoExt);
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

function groupMetadataByProperty(metas: ValidationMetadata[]): Map<string, ValidationMetadata[]> {
  const map = new Map<string, ValidationMetadata[]>();
  for (const m of metas) {
    const list = map.get(m.propertyName);
    if (list) list.push(m);
    else map.set(m.propertyName, [m]);
  }
  return map;
}

function main() {
  const files = findAllDtoFiles();
  const allClassesByFile = new Map<string, ScannedDtoClass[]>();
  const allClasses: ScannedDtoClass[] = [];

  for (const file of files) {
    const classes = scanDtoFile(file);
    allClassesByFile.set(file, classes);
    allClasses.push(...classes);
  }

  // --- Pass 1: build the global registry (className -> every class sharing that name) ---
  const registry: ClassRegistry = new Map();
  for (const scanned of allClasses) {
    const outRelativePath = computeOutRelativePath(scanned.relativePath);
    const entry: ClassRegistryEntry = {
      className: scanned.className,
      schemaVarName: schemaVarNameFor(scanned.className),
      sourceFilePath: scanned.filePath,
      outRelativePath,
    };
    const list = registry.get(scanned.className);
    if (list) list.push(entry);
    else registry.set(scanned.className, [entry]);
  }

  const unrecognizedReport: string[] = [];
  const generatedOutRelativePaths: string[] = [];
  const exportedNamesByFile = new Map<string, string[]>();
  let totalClasses = 0;
  let totalProperties = 0;

  // --- Pass 2: per source file, require it for real and translate every class ---
  for (const file of files) {
    const classes = allClassesByFile.get(file)!;
    if (classes.length === 0) continue;

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const mod = require(file);
    const outRelativePath = computeOutRelativePath(classes[0].relativePath);

    // Topologically order classes declared in THIS file so a nested reference to a sibling
    // class in the same file is always emitted after the class it depends on.
    const ordered = topoSortSameFile(classes, registry);

    const importsNeeded = new Map<string, Set<string>>(); // outRelativePath -> set of schemaVarName
    const blocks: string[] = [];

    for (const scanned of ordered) {
      const ctor = mod[scanned.className];
      if (typeof ctor !== "function") {
        throw new Error(
          `generate-zod-schemas: "${scanned.className}" was found by the source scan in ${file} but is not an ` +
            `exported class at runtime (module exports: ${Object.keys(mod).join(", ")}) — codegen cannot proceed.`,
        );
      }
      const metas = getMetadataStorage().getTargetValidationMetadatas(ctor, "", false, false);
      const byProp = groupMetadataByProperty(metas);

      const propLines: string[] = [];
      let classIsSelfReferential = false;
      for (const prop of scanned.properties) {
        const propMetas = byProp.get(prop.name) ?? [];
        const result = translateProperty(prop, propMetas, registry, scanned);
        totalProperties += 1;

        if (result.referencedClassNames.has(scanned.className)) classIsSelfReferential = true;

        for (const refName of result.referencedClassNames) {
          const refEntry = resolveClassRef(refName, scanned, registry);
          if (refEntry && refEntry.outRelativePath !== outRelativePath) {
            const set = importsNeeded.get(refEntry.outRelativePath) ?? new Set<string>();
            set.add(refEntry.schemaVarName);
            importsNeeded.set(refEntry.outRelativePath, set);
          }
        }

        if (result.unrecognized.length > 0) {
          unrecognizedReport.push(
            `${scanned.relativePath}::${scanned.className}.${prop.name}: ${result.unrecognized.join(", ")}`,
          );
        }

        const keyLiteral = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(prop.name) ? prop.name : JSON.stringify(prop.name);
        propLines.push(`    ${keyLiteral}: ${result.expr},`);
      }

      const schemaVarName = schemaVarNameFor(scanned.className);
      const ownShape = `z.object({\n${propLines.join("\n")}\n})`;
      let fullExpr = ownShape;

      if (scanned.extendsClassName) {
        const parentEntry = resolveClassRef(scanned.extendsClassName, scanned, registry);
        if (parentEntry) {
          if (parentEntry.outRelativePath !== outRelativePath) {
            const set = importsNeeded.get(parentEntry.outRelativePath) ?? new Set<string>();
            set.add(parentEntry.schemaVarName);
            importsNeeded.set(parentEntry.outRelativePath, set);
          }
          fullExpr = propLines.length > 0 ? `${parentEntry.schemaVarName}.merge(${ownShape})` : parentEntry.schemaVarName;
        } else {
          unrecognizedReport.push(
            `${scanned.relativePath}::${scanned.className}: extends "${scanned.extendsClassName}", but that base class was not found in the registry — emitting own properties only (base fields NOT mirrored).`,
          );
        }
      }

      if (classIsSelfReferential) {
        // A property (directly, or via array/nested) refers back to this very class (e.g.
        // `AccountTreeNodeResponseDto.children: AccountTreeNodeResponseDto[]`). The per-property
        // translator already wraps that reference in `z.lazy(() => ${schemaVarName})`
        // (decorator-to-zod.ts's `isSelfReference` check), which defers the RUNTIME reference —
        // but TypeScript still cannot INFER the const's own type from an initializer that refers
        // to itself (a real "implicitly has type any" circular-inference error, not a codegen
        // bug — see zod's own recursive-types documentation), so the const needs an explicit
        // `z.ZodType<T>` annotation to break that cycle. `T` is emitted as a plain TS interface
        // built straight from the DTO's own declared property types (already valid TypeScript —
        // every other generated schema file exports a `type <ClassName>` alias under the exact
        // same identifier, so a same-name cross-reference inside the interface resolves for
        // free) rather than the usual `type X = z.infer<typeof XSchema>` pattern, which would
        // hit the exact same circularity one level up.
        const extendsClause = scanned.extendsClassName ? ` extends ${scanned.extendsClassName}` : "";
        if (scanned.extendsClassName) {
          const parentEntry = resolveClassRef(scanned.extendsClassName, scanned, registry);
          if (parentEntry && parentEntry.outRelativePath !== outRelativePath) {
            const set = importsNeeded.get(parentEntry.outRelativePath) ?? new Set<string>();
            set.add(parentEntry.className); // the plain TYPE, needed by the `extends` clause below
            importsNeeded.set(parentEntry.outRelativePath, set);
          }
        }
        const interfaceMembers = scanned.properties.map(p => {
          const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(p.name) ? p.name : JSON.stringify(p.name);
          return `  ${key}${p.optionalToken ? "?" : ""}: ${p.typeText};`;
        });
        blocks.push(
          `export interface ${scanned.className}${extendsClause} {\n${interfaceMembers.join("\n")}\n}\n` +
            `export const ${schemaVarName}: z.ZodType<${scanned.className}> = ${fullExpr};\n`,
        );
      } else {
        blocks.push(
          `export const ${schemaVarName} = ${fullExpr};\nexport type ${scanned.className} = z.infer<typeof ${schemaVarName}>;\n`,
        );
      }
      exportedNamesByFile.set(outRelativePath, [
        ...(exportedNamesByFile.get(outRelativePath) ?? []),
        scanned.className,
        schemaVarName,
      ]);
      totalClasses += 1;
    }

    const importLines: string[] = [`import { z } from "zod";`];
    for (const [refOutPath, names] of [...importsNeeded.entries()].sort()) {
      const specifier = computeImportSpecifier(outRelativePath, refOutPath);
      importLines.push(`import { ${[...names].sort().join(", ")} } from "${specifier}";`);
    }

    const content = `${GENERATED_BANNER}${importLines.join("\n")}\n\n${blocks.join("\n")}`;
    const outAbsolute = path.join(CONTRACTS_SRC, outRelativePath);
    fs.mkdirSync(path.dirname(outAbsolute), { recursive: true });
    fs.writeFileSync(outAbsolute, content, "utf8");
    generatedOutRelativePaths.push(outRelativePath);
  }

  // --- Barrel ---
  // Several DTO class names repeat verbatim across unrelated modules (see decorator-to-zod.ts's
  // own doc comment — e.g. `CreateCategoryDto` in both domains/inventory and domains/expenses),
  // so a flat `export *` from every generated file is not safe: TS rejects re-exporting two
  // different symbols under the same bare name (TS2308). Every file's exports stay reachable
  // from this barrel regardless — files whose exported names are all still unclaimed get the
  // normal flat `export *`; the first file to introduce a colliding name keeps the flat form
  // (first-come, alphabetical by output path), and every LATER file that collides with an
  // already-claimed name is re-exported under a namespace derived from its own path instead
  // (`export * as domains_expenses_category from "./domains/expenses/category.schema"`) — no
  // schema is ever silently dropped from the barrel, a name collision only changes HOW it's
  // reached from here. Direct deep imports (`@klickit/contracts/domains/expenses/category.schema`,
  // the tsconfig `paths` alias every consumer already has) remain the unambiguous way to reach
  // any one schema regardless, same as `packages/server`'s own DTOs are never imported through
  // one flat barrel either.
  const barrelLines: string[] = [
    "/**",
    " * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts — see that file.",
    " * Re-exports every generated zod schema plus the OpenAPI-derived types and typed client.",
    " * See this file's own generator for why some entries are namespaced instead of flat",
    " * (duplicate DTO class names across unrelated modules — e.g. CreateCategoryDto exists in",
    " * both domains/inventory and domains/expenses).",
    " */",
    'export * from "./generated/openapi-types";',
    'export * from "./client";',
    "",
  ];
  const claimedNames = new Set<string>();
  for (const outRelativePath of generatedOutRelativePaths.sort()) {
    const specifier = `./${outRelativePath.replace(/\.ts$/, "")}`;
    const names = exportedNamesByFile.get(outRelativePath) ?? [];
    const collides = names.some(n => claimedNames.has(n));
    if (!collides) {
      for (const n of names) claimedNames.add(n);
      barrelLines.push(`export * from "${specifier}";`);
    } else {
      const alias = outRelativePath.replace(/\.ts$/, "").replace(/[^A-Za-z0-9]+/g, "_");
      barrelLines.push(`export * as ${alias} from "${specifier}";`);
    }
  }
  fs.writeFileSync(path.join(CONTRACTS_SRC, "index.ts"), `${barrelLines.join("\n")}\n`, "utf8");

  console.log(`generate-zod-schemas: ${totalClasses} DTO classes, ${totalProperties} properties translated.`);
  console.log(`generate-zod-schemas: ${generatedOutRelativePaths.length} schema files written under src/.`);
  if (unrecognizedReport.length > 0) {
    console.log(
      `generate-zod-schemas: ${unrecognizedReport.length} property/decorator combinations fell back to a permissive ` +
        `schema (property key always present — see each list entry for what wasn't precisely translated):`,
    );
    for (const line of unrecognizedReport) console.log(`  - ${line}`);
  } else {
    console.log("generate-zod-schemas: every property translated with no fallback — full decorator coverage.");
  }
}

/** Order classes within one source file so a same-file nested reference is declared before its user. */
function topoSortSameFile(classes: ScannedDtoClass[], registry: ClassRegistry): ScannedDtoClass[] {
  const byName = new Map(classes.map(c => [c.className, c]));
  const visited = new Set<string>();
  const out: ScannedDtoClass[] = [];

  function referencedSameFileNames(scanned: ScannedDtoClass): string[] {
    const names: string[] = [];
    if (scanned.extendsClassName && byName.has(scanned.extendsClassName)) {
      names.push(scanned.extendsClassName);
    }
    for (const prop of scanned.properties) {
      const typeDecorator = prop.decorators.find(d => d.name === "Type");
      if (typeDecorator?.arrowReturnIdentifier && byName.has(typeDecorator.arrowReturnIdentifier)) {
        names.push(typeDecorator.arrowReturnIdentifier);
      }
    }
    return names;
  }

  function visit(scanned: ScannedDtoClass) {
    if (visited.has(scanned.className)) return;
    visited.add(scanned.className);
    for (const depName of referencedSameFileNames(scanned)) {
      const dep = byName.get(depName);
      if (dep) visit(dep);
    }
    out.push(scanned);
  }

  for (const c of classes) visit(c);
  return out;
}

main();
