/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const PaginationQueryDtoSchema = z.object({
    page: z.number().min(1).int().optional(),
    pageSize: z.number().max(200).min(1).int().optional(),
    sortBy: z.string().optional(),
    sortDir: z.enum(["ASC", "DESC"]).optional(),
});
export type PaginationQueryDto = z.infer<typeof PaginationQueryDtoSchema>;
