/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const ThemeColorsDtoSchema = z.object({
    primary: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
    secondary: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
    accent: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
    primaryLight: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
    primarySoft: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
    primaryLavender: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
    surface: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
    dark: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
    black: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
});
export type ThemeColorsDto = z.infer<typeof ThemeColorsDtoSchema>;

export const ThemeRadiusDtoSchema = z.object({
    sm: z.string().max(20),
    md: z.string().max(20),
    lg: z.string().max(20),
    xl: z.string().max(20),
});
export type ThemeRadiusDto = z.infer<typeof ThemeRadiusDtoSchema>;

export const ThemeSpacingDtoSchema = z.object({
    xs: z.string().max(20),
    sm: z.string().max(20),
    md: z.string().max(20),
    lg: z.string().max(20),
    xl: z.string().max(20),
    xxl: z.string().max(20),
    xxxl: z.string().max(20),
});
export type ThemeSpacingDto = z.infer<typeof ThemeSpacingDtoSchema>;

export const ThemeTokensDtoSchema = z.object({
    colors: ThemeColorsDtoSchema,
    fontFamily: z.string().max(100),
    radius: ThemeRadiusDtoSchema,
    spacing: ThemeSpacingDtoSchema,
});
export type ThemeTokensDto = z.infer<typeof ThemeTokensDtoSchema>;
