/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";
import { DocumentConfigDtoSchema } from "./document-config.schema";
import { LoginConfigDtoSchema } from "./login-config.schema";
import { ThemeTokensDtoSchema } from "./theme-tokens.schema";

export const ThemeResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    status: z.enum(["DRAFT", "PUBLISHED", "ARCHIVED"]),
    tokens: ThemeTokensDtoSchema,
    logoFileId: z.string().nullable(),
    faviconFileId: z.string().nullable(),
    loginConfig: LoginConfigDtoSchema,
    documentConfig: DocumentConfigDtoSchema,
    publishedAt: z.coerce.date().nullable(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    createdBy: z.string().nullable(),
    updatedBy: z.string().nullable(),
    version: z.number(),
});
export type ThemeResponseDto = z.infer<typeof ThemeResponseDtoSchema>;
