/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateFaAssetDtoSchema = z.object({
    code: z.string(),
    name: z.string(),
    categoryId: z.string().uuid(),
    serialNo: z.string().optional(),
    barcode: z.string().optional(),
    location: z.string(),
    custodianUserId: z.string().uuid().optional(),
    acquisitionDate: z.string(),
    cost: z.string().regex(/^-?\d+(\.\d+)?$/),
    fundingSource: z.enum(["SCHOOL", "GRANT", "DONOR"]),
    supplierId: z.string().uuid().optional(),
    poId: z.string().uuid().optional(),
    grnId: z.string().uuid().optional(),
    inServiceFrom: z.string(),
    lifeMonthsOverride: z.number().positive().int().optional(),
    residualValue: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    insurance: z.record(z.string(), z.unknown()).optional(),
    condition: z.string().optional(),
    photos: z.array(z.string().uuid()).optional(),
});
export type CreateFaAssetDto = z.infer<typeof CreateFaAssetDtoSchema>;

export const UpdateFaAssetDtoSchema = z.object({
    name: z.string().optional(),
    categoryId: z.string().uuid().optional(),
    serialNo: z.string().optional(),
    barcode: z.string().optional(),
    location: z.string().optional(),
    custodianUserId: z.string().uuid().optional(),
    lifeMonthsOverride: z.number().positive().int().optional(),
    residualValue: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    insurance: z.record(z.string(), z.unknown()).optional(),
    condition: z.string().optional(),
    photos: z.array(z.string().uuid()).optional(),
});
export type UpdateFaAssetDto = z.infer<typeof UpdateFaAssetDtoSchema>;

export const UpdateFaAssetConditionDtoSchema = z.object({
    condition: z.string(),
});
export type UpdateFaAssetConditionDto = z.infer<typeof UpdateFaAssetConditionDtoSchema>;

export const FaAssetResponseDtoSchema = z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    categoryId: z.string(),
    serialNo: z.string().nullable(),
    barcode: z.string().nullable(),
    location: z.string(),
    custodianUserId: z.string().nullable(),
    acquisitionDate: z.string(),
    cost: z.string(),
    fundingSource: z.string(),
    supplierId: z.string().nullable(),
    poId: z.string().nullable(),
    grnId: z.string().nullable(),
    inServiceFrom: z.string(),
    lifeMonthsOverride: z.number().nullable(),
    residualValue: z.string(),
    accumDepreciation: z.string(),
    status: z.string(),
    insurance: z.record(z.string(), z.unknown()).nullable(),
    condition: z.string(),
    photos: z.array(z.string()).nullable(),
});
export type FaAssetResponseDto = z.infer<typeof FaAssetResponseDtoSchema>;
