/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateFaCategoryDtoSchema = z.object({
    name: z.string(),
    method: z.enum(["SL", "RB"]),
    lifeMonths: z.number().positive().int(),
    rate: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    residualPct: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    glCostAccountId: z.string().uuid(),
    glAccumDepAccountId: z.string().uuid(),
    glDepExpenseAccountId: z.string().uuid(),
});
export type CreateFaCategoryDto = z.infer<typeof CreateFaCategoryDtoSchema>;

export const UpdateFaCategoryDtoSchema = z.object({
    name: z.string().optional(),
    method: z.enum(["SL", "RB"]).optional(),
    lifeMonths: z.number().positive().int().optional(),
    rate: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    residualPct: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    glCostAccountId: z.string().uuid().optional(),
    glAccumDepAccountId: z.string().uuid().optional(),
    glDepExpenseAccountId: z.string().uuid().optional(),
});
export type UpdateFaCategoryDto = z.infer<typeof UpdateFaCategoryDtoSchema>;

export const FaCategoryResponseDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    method: z.string(),
    lifeMonths: z.number(),
    rate: z.string().nullable(),
    residualPct: z.string(),
    glCostAccountId: z.string(),
    glAccumDepAccountId: z.string(),
    glDepExpenseAccountId: z.string(),
});
export type FaCategoryResponseDto = z.infer<typeof FaCategoryResponseDtoSchema>;
