/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateFaDepreciationRunDtoSchema = z.object({
    periodId: z.string().uuid(),
});
export type CreateFaDepreciationRunDto = z.infer<typeof CreateFaDepreciationRunDtoSchema>;

export const DecideFaDepreciationRunDtoSchema = z.object({
    decision: z.enum(["APPROVE", "RETURN"]),
});
export type DecideFaDepreciationRunDto = z.infer<typeof DecideFaDepreciationRunDtoSchema>;

export const FaDepreciationRunResponseDtoSchema = z.object({
    id: z.string(),
    periodId: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
});
export type FaDepreciationRunResponseDto = z.infer<typeof FaDepreciationRunResponseDtoSchema>;

export const FaDepreciationLineResponseDtoSchema = z.object({
    id: z.string(),
    runId: z.string(),
    assetId: z.string(),
    amount: z.string(),
    nbvAfter: z.string(),
});
export type FaDepreciationLineResponseDto = z.infer<typeof FaDepreciationLineResponseDtoSchema>;
