/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateFaDisposalDtoSchema = z.object({
    assetId: z.string().uuid(),
    method: z.enum(["SALE", "SCRAP", "DONATION", "WRITE_OFF"]),
    proceeds: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
});
export type CreateFaDisposalDto = z.infer<typeof CreateFaDisposalDtoSchema>;

export const DecideFaDisposalDtoSchema = z.object({
    decision: z.enum(["APPROVE", "RETURN"]),
});
export type DecideFaDisposalDto = z.infer<typeof DecideFaDisposalDtoSchema>;

export const FaDisposalResponseDtoSchema = z.object({
    id: z.string(),
    assetId: z.string(),
    method: z.string(),
    proceeds: z.string(),
    gainLoss: z.string().nullable(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
});
export type FaDisposalResponseDto = z.infer<typeof FaDisposalResponseDtoSchema>;
