/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const ScheduleFaMaintenanceDtoSchema = z.object({
    assetId: z.string().uuid(),
    kind: z.enum(["PLANNED", "REPAIR"]),
    scheduledOn: z.string().optional(),
    downtimeNote: z.string().optional(),
});
export type ScheduleFaMaintenanceDto = z.infer<typeof ScheduleFaMaintenanceDtoSchema>;

export const CompleteFaMaintenanceDtoSchema = z.object({
    doneOn: z.string(),
    downtimeNote: z.string().optional(),
    costExpenseVoucherId: z.string().uuid().optional(),
});
export type CompleteFaMaintenanceDto = z.infer<typeof CompleteFaMaintenanceDtoSchema>;

export const FaMaintenanceResponseDtoSchema = z.object({
    id: z.string(),
    assetId: z.string(),
    kind: z.string(),
    scheduledOn: z.string().nullable(),
    doneOn: z.string().nullable(),
    costExpenseVoucherId: z.string().nullable(),
    downtimeNote: z.string(),
});
export type FaMaintenanceResponseDto = z.infer<typeof FaMaintenanceResponseDtoSchema>;
