/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateFaTransferDtoSchema = z.object({
    assetId: z.string().uuid(),
    toLocation: z.string(),
    toCustodianUserId: z.string().uuid().optional(),
});
export type CreateFaTransferDto = z.infer<typeof CreateFaTransferDtoSchema>;

export const FaTransferResponseDtoSchema = z.object({
    id: z.string(),
    assetId: z.string(),
    fromLocation: z.string(),
    fromCustodianUserId: z.string().nullable(),
    toLocation: z.string(),
    toCustodianUserId: z.string().nullable(),
    ackBy: z.string().nullable(),
    at: z.coerce.date(),
});
export type FaTransferResponseDto = z.infer<typeof FaTransferResponseDtoSchema>;
