/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const FaVerificationScopeDtoSchema = z.object({
    assetIds: z.union([z.array(z.string()), z.literal("ALL")]),
});
export type FaVerificationScopeDto = z.infer<typeof FaVerificationScopeDtoSchema>;

export const CreateFaVerificationDtoSchema = z.object({
    scope: FaVerificationScopeDtoSchema,
});
export type CreateFaVerificationDto = z.infer<typeof CreateFaVerificationDtoSchema>;

export const RecordVerificationCountDtoSchema = z.object({
    lineId: z.string().uuid(),
    found: z.boolean(),
    condition: z.string().optional(),
    notes: z.string().optional(),
});
export type RecordVerificationCountDto = z.infer<typeof RecordVerificationCountDtoSchema>;

export const RecordVerificationCountsDtoSchema = z.object({
    counts: z.array(RecordVerificationCountDtoSchema).min(1),
});
export type RecordVerificationCountsDto = z.infer<typeof RecordVerificationCountsDtoSchema>;

export const DecideFaVerificationDtoSchema = z.object({
    decision: z.enum(["APPROVE", "RETURN"]),
});
export type DecideFaVerificationDto = z.infer<typeof DecideFaVerificationDtoSchema>;

export const FaVerificationResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    scope: z.record(z.string(), z.unknown()),
    snapshotAt: z.coerce.date(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
});
export type FaVerificationResponseDto = z.infer<typeof FaVerificationResponseDtoSchema>;

export const FaVerificationLineResponseDtoSchema = z.object({
    id: z.string(),
    verificationId: z.string(),
    assetId: z.string(),
    found: z.boolean(),
    condition: z.string().nullable(),
    notes: z.string().nullable(),
});
export type FaVerificationLineResponseDto = z.infer<typeof FaVerificationLineResponseDtoSchema>;

export const PostFaVerificationResponseDtoSchema = z.object({
    verification: FaVerificationResponseDtoSchema,
    missingAssetIds: z.array(z.string()),
});
export type PostFaVerificationResponseDto = z.infer<typeof PostFaVerificationResponseDtoSchema>;
