/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateStudentDtoSchema = z.object({
    admissionNo: z.string().max(30).optional(),
    firstName: z.string().max(60),
    middleName: z.string().max(60).optional(),
    lastName: z.string().max(60),
    classId: z.string().uuid(),
    streamId: z.string().uuid().optional(),
    boarding: z.enum(["DAY", "BOARDER"]).optional(),
    feeGroupId: z.string().uuid().optional(),
    sponsorId: z.string().uuid().optional(),
    transportRouteId: z.string().uuid().optional(),
    photoFileId: z.string().uuid().optional(),
    customFields: z.record(z.string(), z.unknown()).optional(),
    enrolledOn: z.string(),
});
export type CreateStudentDto = z.infer<typeof CreateStudentDtoSchema>;
