/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const GuardianResponseDtoSchema = z.object({
    id: z.string(),
    fullName: z.string(),
    phone: z.string().nullable(),
    email: z.string().nullable(),
    nationalId: z.string().nullable(),
    userId: z.string().nullable(),
});
export type GuardianResponseDto = z.infer<typeof GuardianResponseDtoSchema>;

export const CreateGuardianResponseDtoSchema = GuardianResponseDtoSchema.merge(z.object({
    wasExisting: z.boolean(),
}));
export type CreateGuardianResponseDto = z.infer<typeof CreateGuardianResponseDtoSchema>;

export const GuardianListItemResponseDtoSchema = GuardianResponseDtoSchema.merge(z.object({
    studentCount: z.number(),
}));
export type GuardianListItemResponseDto = z.infer<typeof GuardianListItemResponseDtoSchema>;

export const StudentGuardianLinkResponseDtoSchema = z.object({
    id: z.string(),
    studentId: z.string(),
    guardianId: z.string(),
    relationship: z.string(),
    isPrimary: z.boolean(),
    receivesBilling: z.boolean(),
});
export type StudentGuardianLinkResponseDto = z.infer<typeof StudentGuardianLinkResponseDtoSchema>;
