/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const LedgerStatementRowDtoSchema = z.object({
    id: z.string(),
    studentId: z.string(),
    entryDate: z.string(),
    postedAt: z.coerce.date(),
    docType: z.string(),
    docId: z.string(),
    docNumber: z.string(),
    debit: z.string(),
    credit: z.string(),
    memo: z.string().nullable(),
    runningBalance: z.string(),
});
export type LedgerStatementRowDto = z.infer<typeof LedgerStatementRowDtoSchema>;
