/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const StudentResponseDtoSchema = z.object({
    id: z.string(),
    admissionNo: z.string(),
    firstName: z.string(),
    middleName: z.string().nullable(),
    lastName: z.string(),
    searchName: z.string(),
    classId: z.string(),
    streamId: z.string().nullable(),
    status: z.string(),
    boarding: z.string(),
    feeGroupId: z.string().nullable(),
    sponsorId: z.string().nullable(),
    transportRouteId: z.string().nullable(),
    photoFileId: z.string().nullable(),
    customFields: z.record(z.string(), z.unknown()),
    enrolledOn: z.string(),
    exitedOn: z.string().nullable(),
    exitCleared: z.boolean(),
});
export type StudentResponseDto = z.infer<typeof StudentResponseDtoSchema>;
